//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 08-Dec-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//



#include "TIMETRACETP_userdef.h"
#include "metaiv.h"
#include "TIMETRACETP.h"
#include "AS.h"
#include "INSTRTP.h"
#include "SCHDTP.h"
#include "SEM.h"
