//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 21-Oct-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _TRF_uTAR_uDEF_h
#define _TRF_uTAR_uDEF_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CI.h"
#include "EXP_uPAT.h"
#include "REP.h"
#include "TRF_uCAST.h"
#include "TRF_uTAR_uEXPR.h"
#include "TRF_uTAR_uPAT.h"
#include "TRF_uTAR_uTYPE.h"
#include "TRF_uTAR_uDEF_anonym.h"
enum  {
  vdm_TRF_uTAR_uDEF_FnBody = TAG_TYPE_TRF_uTAR_uDEF_FnBody,
  length_TRF_uTAR_uDEF_FnBody = 2,
  pos_TRF_uTAR_uDEF_FnBody_body = 1,
  pos_TRF_uTAR_uDEF_FnBody_cid = 2,
  vdm_TRF_uTAR_uDEF_PATTYPEPAIR = TAG_TYPE_TRF_uTAR_uDEF_PATTYPEPAIR,
  length_TRF_uTAR_uDEF_PATTYPEPAIR = 3,
  pos_TRF_uTAR_uDEF_PATTYPEPAIR_pat = 1,
  pos_TRF_uTAR_uDEF_PATTYPEPAIR_tp = 2,
  pos_TRF_uTAR_uDEF_PATTYPEPAIR_cid = 3,
  vdm_TRF_uTAR_uDEF_ValueDef = TAG_TYPE_TRF_uTAR_uDEF_ValueDef,
  length_TRF_uTAR_uDEF_ValueDef = 3,
  pos_TRF_uTAR_uDEF_ValueDef_val = 1,
  pos_TRF_uTAR_uDEF_ValueDef_fv = 2,
  pos_TRF_uTAR_uDEF_ValueDef_pid = 3
};

class TYPE_TRF_uTAR_uDEF_FnBody : public Record {
public:

  TYPE_TRF_uTAR_uDEF_FnBody() : Record(TAG_TYPE_TRF_uTAR_uDEF_FnBody, 2) {}
  void Init(Generic p2, TYPE_CI_ContextId p3);

  TYPE_TRF_uTAR_uDEF_FnBody(const Generic &c) : Record(c) {}

  const char * GetTypeName() const { return "TYPE_TRF_uTAR_uDEF_FnBody"; }
  Generic get_body() const;
  void set_body(const Generic &p);
  TYPE_CI_ContextId get_cid() const;
  void set_cid(const TYPE_CI_ContextId &p);
} ;

class TYPE_TRF_uTAR_uDEF_PATTYPEPAIR : public Record {
public:

  TYPE_TRF_uTAR_uDEF_PATTYPEPAIR() : Record(TAG_TYPE_TRF_uTAR_uDEF_PATTYPEPAIR, 3) {}
  void Init(TYPE_TRF_uTAR_uPAT_Pattern p2, TYPE_TRF_uTAR_uTYPE_Type p3, TYPE_CI_ContextId p4);

  TYPE_TRF_uTAR_uDEF_PATTYPEPAIR(const Generic &c) : Record(c) {}

  const char * GetTypeName() const { return "TYPE_TRF_uTAR_uDEF_PATTYPEPAIR"; }
  TYPE_TRF_uTAR_uPAT_Pattern get_pat() const;
  void set_pat(const TYPE_TRF_uTAR_uPAT_Pattern &p);
  TYPE_TRF_uTAR_uTYPE_Type get_tp() const;
  void set_tp(const TYPE_TRF_uTAR_uTYPE_Type &p);
  TYPE_CI_ContextId get_cid() const;
  void set_cid(const TYPE_CI_ContextId &p);
} ;

class TYPE_TRF_uTAR_uDEF_ValueDef : public Record {
public:

  TYPE_TRF_uTAR_uDEF_ValueDef() : Record(TAG_TYPE_TRF_uTAR_uDEF_ValueDef, 3) {}
  void Init(TYPE_AS_ValueDef p2, TYPE_TRF_uTAR_uEXPR_Identifiers p3, TYPE_TRF_uTAR_uPAT_PatternIds p4);

  TYPE_TRF_uTAR_uDEF_ValueDef(const Generic &c) : Record(c) {}

  const char * GetTypeName() const { return "TYPE_TRF_uTAR_uDEF_ValueDef"; }
  TYPE_AS_ValueDef get_val() const;
  void set_val(const TYPE_AS_ValueDef &p);
  TYPE_TRF_uTAR_uEXPR_Identifiers get_fv() const;
  void set_fv(const TYPE_TRF_uTAR_uEXPR_Identifiers &p);
  TYPE_TRF_uTAR_uPAT_PatternIds get_pid() const;
  void set_pid(const TYPE_TRF_uTAR_uPAT_PatternIds &p);
} ;
void init_TRF_uTAR_uDEF();
TYPE_TRF_uTAR_uDEF_Parameters vdm_TRF_uTAR_uDEF_ComputeNewParameters(const TYPE_TRF_uTAR_uDEF_Parameters &, const TYPE_TRF_uTAR_uEXPR_Identifiers &);
type_dL vdm_TRF_uTAR_uDEF_ExtractLocalDefs(const TYPE_TRF_uTAR_uDEF_Parameters &, const TYPE_TRF_uTAR_uDEF_Parameters &);
Bool vdm_TRF_uTAR_uDEF_pre_ExtractLocalDefs(const TYPE_TRF_uTAR_uDEF_Parameters &, const TYPE_TRF_uTAR_uDEF_Parameters &);
TYPE_CI_ContextId vdm_TRF_uTAR_uDEF_MakeNewContextInfo(const TYPE_REP_TypeRep &, const TYPE_CI_ContextId &);
Bool vdm_TRF_uTAR_uDEF_pre_MakeNewContextInfo(const TYPE_REP_TypeRep &, const TYPE_CI_ContextId &);
Bool vdm_TRF_uTAR_uDEF_post_MakeNewContextInfo(const TYPE_REP_TypeRep &, const TYPE_CI_ContextId &, const TYPE_CI_ContextId &);
Bool vdm_TRF_uTAR_uDEF_NewSetTypeInfo(const TYPE_CI_ContextId &, const TYPE_REP_TypeRep &);
Bool vdm_TRF_uTAR_uDEF_pre_NewSetTypeInfo(const TYPE_CI_ContextId &, const TYPE_REP_TypeRep &);
Bool vdm_TRF_uTAR_uDEF_post_NewSetTypeInfo(const TYPE_CI_ContextId &, const TYPE_REP_TypeRep &, const Bool &);
TYPE_TRF_uTAR_uDEF_AstCI vdm_TRF_uTAR_uDEF_tar_uAstCI(const Generic &, const type_19CI_TokenContextInfoCL &, const TYPE_CI_FileIdMap &);
TYPE_TRF_uTAR_uDEF_Definitions vdm_TRF_uTAR_uDEF_tar_uDefinitions(const type_7AS_NameC10AS_TypeDefCM &, const type_11AS_ValueDefCL &, const type_7AS_NameC12AS_ExplFnDefCM &, const type_7AS_NameCFM &, const Generic &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_Document vdm_TRF_uTAR_uDEF_tar_uDocument(const type_dL &);
TYPE_TRF_uTAR_uDEF_ExplFnDef vdm_TRF_uTAR_uDEF_tar_uExplFunction(const TYPE_TRF_uTAR_uEXPR_NameName &, const TYPE_TRF_uTAR_uDEF_TypeVarList &, const TYPE_TRF_uTAR_uTYPE_FnType &, const TYPE_TRF_uTAR_uDEF_ParametersList &, const TYPE_TRF_uTAR_uDEF_FnBody &, const Generic &, const Generic &, const TYPE_CI_ContextId &);
Bool vdm_TRF_uTAR_uDEF_pre_tar_uExplFunction(const TYPE_TRF_uTAR_uEXPR_NameName &, const TYPE_TRF_uTAR_uDEF_TypeVarList &, const TYPE_TRF_uTAR_uTYPE_FnType &, const TYPE_TRF_uTAR_uDEF_ParametersList &, const TYPE_TRF_uTAR_uDEF_FnBody &, const Generic &, const Generic &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_ExtExplFnDef vdm_TRF_uTAR_uDEF_tar_uExtExplFunction(const TYPE_TRF_uTAR_uEXPR_NameName &, const TYPE_TRF_uTAR_uDEF_TypeVarList &, const TYPE_TRF_uTAR_uDEF_ParameterTypes &, const type_11AS_NameTypeCL &, const TYPE_TRF_uTAR_uDEF_FnBody &, const Generic &, const Generic &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_FnBody vdm_TRF_uTAR_uDEF_tar_uFnBody(const Generic &, const TYPE_CI_ContextId &);
type_11AS_ValueDefCL vdm_TRF_uTAR_uDEF_tar_uGlobalValueDef(const type_22TRF_uTAR_uDEF_ValueDefCL &);
TYPE_TRF_uTAR_uDEF_ImplFnDef vdm_TRF_uTAR_uDEF_tar_uImplFunction(const TYPE_TRF_uTAR_uEXPR_NameName &, const TYPE_TRF_uTAR_uDEF_TypeVarList &, const TYPE_TRF_uTAR_uDEF_ParameterTypes &, const type_11AS_NameTypeCL &, const Generic &, const TYPE_TRF_uTAR_uEXPR_Expr &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_Invariant vdm_TRF_uTAR_uDEF_tar_uInvariant(const TYPE_TRF_uTAR_uPAT_Pattern &, const TYPE_TRF_uTAR_uEXPR_Expr &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_Module vdm_TRF_uTAR_uDEF_tar_uModule(const TYPE_TRF_uTAR_uEXPR_NameName &, const TYPE_TRF_uTAR_uDEF_Interface &, const TYPE_TRF_uTAR_uDEF_Definitions &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_NameType vdm_TRF_uTAR_uDEF_tar_uNameType(const TYPE_TRF_uTAR_uEXPR_NameName &, const TYPE_TRF_uTAR_uTYPE_Type &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_PatTypePair vdm_TRF_uTAR_uDEF_tar_uPatTypePair(const type_FL &, const TYPE_TRF_uTAR_uTYPE_Type &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_TypeDef vdm_TRF_uTAR_uDEF_tar_uTypeDef(const TYPE_TRF_uTAR_uEXPR_NameType &, const TYPE_AS_Type &, const TYPE_TRF_uTAR_uTYPE_Type &, const Generic &, const TYPE_CI_ContextId &);
TYPE_TRF_uTAR_uDEF_ValueDef vdm_TRF_uTAR_uDEF_tar_uValueDef(const TYPE_TRF_uTAR_uPAT_Pattern &, const Generic &, const TYPE_TRF_uTAR_uEXPR_Expr &, const TYPE_CI_ContextId &);

#endif

