//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 21-Oct-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//



#include "TRF_uCAST_userdef.h"
#include "metaiv.h"
#include "TRF_uCAST.h"
#include "AS.h"
#include "CI.h"
#include "REP.h"
#include "TRF_uTAR_uEXPR.h"
#include "TRF_uTRA_uEXPR.h"
