//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 21-Oct-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _TRF_uTRA_uEXPR_h
#define _TRF_uTRA_uEXPR_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CI.h"
#include "REP.h"
#include "TRF_uTAR_uDEF.h"
#include "TRF_uTAR_uEXPR.h"
#include "TRF_uTAR_uPAT.h"
#include "TRF_uTAR_uTYPE.h"
#include "TRF_uTRA_uDEF.h"
#include "TRF_uTRA_uPAT.h"
#include "TRF_uTRA_uTYPE.h"
#include "TRF_uTRA_uEXPR_anonym.h"
;
void init_TRF_uTRA_uEXPR();
TYPE_TRF_uTAR_uEXPR_Expr vdm_TRF_uTRA_uEXPR_trv_uExpr(const TYPE_AS_Expr &);
TYPE_TRF_uTAR_uEXPR_Ids vdm_TRF_uTRA_uEXPR_trv_uIds(const TYPE_AS_Ids &);
TYPE_TRF_uTAR_uEXPR_NameExpr vdm_TRF_uTRA_uEXPR_trv_uNameExpr(const TYPE_AS_Name &);
TYPE_TRF_uTAR_uEXPR_NameName vdm_TRF_uTRA_uEXPR_trv_uNameName(const TYPE_AS_Name &);
TYPE_TRF_uTAR_uEXPR_NameType vdm_TRF_uTRA_uEXPR_trv_uNameType(const TYPE_AS_Name &);

#endif

