#  Programming language Static semantics and dynamic semantics spec

TARGETS = proglang.vdm.gz proglang.ps.gz

BASEFILE = proglang

proglang.vdm.gz : proglang.vdm

proglang.ps.gz : proglang.vdm.ps

include ../Make.rules
