[ mk_Test`BeaconsMet( 
     [ mk_Test`TIVD( 60 ) ],
     [  ] ),
  mk_Test`BeaconsMet( 
     [ mk_Test`TIVD( 60 ),
       mk_Test`TIVD( 40 ) ],
     [  ] ),
  mk_Test`BeaconsMet( 
     [ mk_Test`TIVD( 60 ),
       mk_Test`TIVD( 40 ),
       mk_Test`TIVD( 70 ) ],
     [  ] ),
  mk_Test`BeaconsMet( 
     [ mk_Test`TIVD( 40 ),
       mk_Test`TIVD( 70 ) ],
     [ mk_Test`TIVE( 60 ) ] ),
  mk_Test`BeaconsMet( 
     [ mk_Test`TIVD( 70 ) ],
     [ mk_Test`TIVE( 60 ),
       mk_Test`TIVE( 40 ) ] ),
  mk_Test`BeaconsMet( 
     [ mk_Test`TIVD( 70 ) ],
     [ mk_Test`TIVE( 60 ),
       mk_Test`TIVE( 40 ) ] ),
  mk_Test`BeaconsMet( 
     [  ],
     [ mk_Test`TIVE( 60 ),
       mk_Test`TIVE( 40 ),
       mk_Test`TIVE( 70 ) ] ),
  mk_Test`BeaconsMet( 
     [  ],
     [ mk_Test`TIVE( 40 ),
       mk_Test`TIVE( 70 ) ] ),
  mk_Test`BeaconsMet( 
     [  ],
     [ mk_Test`TIVE( 70 ) ] ) ]
