#!/bin/sh   

## Runs a VDM test example for one argument file.

## Output the argument to stdout (for redirect) and
## "/dev/tty" (for user feedback)
echo "VDM Test: '$1'" > /dev/tty
echo "VDM Test: '$1'"

SPEC="../Beacon.rtf ../CabDisplay.rtf ../CheckSpeedEvent.rtf ../EmergencyBreak.rtf \
      ../Event.rtf ../FLTV.rtf ../HeadMeetBeaconEvent.rtf ../KLV.rtf ../OnBoardComp.rtf \
      ../TIV_A.rtf ../TIV_D.rtf ../TIV_E.rtf ../TailMeetBeaconEvent.rtf ../Test.rtf \
      ../KLVStateEvent.rtf ../NoBeaconMetEvent.rtf ../MaxSpeedEvent.rtf"

## Run the specification with argument while collecting
## test coverage information, and write the result to an
## output file.
vppde -i -R vdm.tc -O $1.res $1 $SPEC

## Check for difference between result of execution
## and expected result.
diff -w $1.res $1.exp
if test $? = 0 ; then
  echo "SUCCESS: Result equals expected result" > /dev/tty
  echo "SUCCESS: Result equals expected result"
else
  echo "FAILURE: Result differs from expected result" > /dev/tty
  echo "FAILURE: Result differs from expected result"
fi

