//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 25-Mar-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//



#include "CON_uENV_userdef.h"
#include "metaiv.h"
#include "CON_uENV.h"
#include "AS.h"
#include "CI.h"
#include "PID.h"
#include "POGTP.h"
#include "REP.h"
#include "SPEC_uAST.h"
#if !DEF_quote_MAYBE && DECL_quote_MAYBE
#define DEF_quote_MAYBE 1
const Quote quote_MAYBE("MAYBE");
#endif

#if !DEF_quote_NO && DECL_quote_NO
#define DEF_quote_NO 1
const Quote quote_NO("NO");
#endif

#if !DEF_quote_NOT_FOUND && DECL_quote_NOT_FOUND
#define DEF_quote_NOT_FOUND 1
const Quote quote_NOT_FOUND("NOT_FOUND");
#endif

