//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 25-Nov-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _GEN_uPO_h
#define _GEN_uPO_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CAST.h"
#include "CHECK.h"
#include "CI.h"
#include "CI_uAUX.h"
#include "CON_uENV.h"
#include "FRESH.h"
#include "POGTP.h"
#include "PURE_uPAT.h"
#include "REP.h"
#include "GEN_uPO_anonym.h"
;
void init_GEN_uPO();
TYPE_AS_Name vdm_GEN_uPO_AddPrefix(const type_cL &, const TYPE_AS_Name &);
TYPE_AS_Expr vdm_GEN_uPO_ApplyPreCondition(const TYPE_AS_FnDef &, const type_FL &);
TYPE_AS_Expr vdm_GEN_uPO_BuildAndExprFromList(const type_FL &);
Bool vdm_GEN_uPO_pre_BuildAndExprFromList(const type_FL &);
TYPE_AS_Expr vdm_GEN_uPO_BuildOrExprFromList(const type_FL &);
Bool vdm_GEN_uPO_pre_BuildOrExprFromList(const type_FL &);
TYPE_AS_Expr vdm_GEN_uPO_BuildPO(const type_FL &, const TYPE_AS_Expr &);
TYPE_AS_Expr vdm_GEN_uPO_BuildVerifyMatch(const TYPE_AS_Expr &, const TYPE_AS_Type &, const TYPE_AS_Pattern &, const type_7AS_NameCS &);
TYPE_POGTP_ProofObligation vdm_GEN_uPO_MakeProofObligation(const TYPE_AS_Expr &, const TYPE_POGTP_Classification &, const TYPE_POGTP_LocContext &, const TYPE_CI_ContextId &);
type_typevariableL vdm_GEN_uPO_SetToSeq(const type_typevariableS &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyApplication(const TYPE_AS_Expr &, const type_FL &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyBinaryOperator(const TYPE_AS_BinaryExpr &, const type_7AS_NameCS &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyCasesExpr(const TYPE_AS_Expr &, const type_11AS_CaseAltnCL &, const Generic &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
Bool vdm_GEN_uPO_pre_VerifyCasesExpr(const TYPE_AS_Expr &, const type_11AS_CaseAltnCL &, const Generic &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyCompatibleMaps(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyComposition(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyDisjunctionOfConjuntionOfPo(const type_FLL &, const TYPE_POGTP_Classification &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyExistsOne(const TYPE_AS_Bind &, const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyFiniteMap(const TYPE_AS_Maplet &, const TYPE_AS_BindList &, const Generic &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyFiniteSet(const TYPE_AS_Expr &, const TYPE_AS_BindList &, const Generic &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyFuncApplication(const TYPE_AS_Expr &, const type_FL &, const TYPE_AS_Type &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
Bool vdm_GEN_uPO_pre_VerifyFuncApplication(const TYPE_AS_Expr &, const type_FL &, const TYPE_AS_Type &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyFunctionComposition(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_AS_Type &, const type_7AS_NameCS &, const TYPE_POGTP_Classification &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
Bool vdm_GEN_uPO_pre_VerifyFunctionComposition(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_AS_Type &, const type_7AS_NameCS &, const TYPE_POGTP_Classification &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyFunctionIteration(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_AS_Type &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
Bool vdm_GEN_uPO_pre_VerifyFunctionIteration(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_AS_Type &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyInvariant(const TYPE_AS_Expr &, const TYPE_AS_Type &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyIteration(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyLetBeSt(const TYPE_AS_Bind &, const Generic &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyMapApplication(const TYPE_AS_Expr &, const type_FL &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
Bool vdm_GEN_uPO_pre_VerifyMapApplication(const TYPE_AS_Expr &, const type_FL &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyMapComp(const TYPE_AS_Maplet &, const TYPE_AS_BindList &, const Generic &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyMapComposition(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyMapInverseInvariant(const TYPE_AS_Expr &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyMapIteration(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyNonEmptySeq(const TYPE_AS_Expr &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyNonEmptySeqInvariant(const TYPE_AS_Expr &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyNonEmptySet(const TYPE_AS_Expr &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyNonEmptySetInvariant(const TYPE_AS_Expr &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyNonEndoIteration(const TYPE_AS_Expr &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyNonZero(const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyNonZeroNatOneInvariant(const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyPatMatch(const TYPE_AS_Name &, const type_15AS_MultTypeBindCL &, const Generic &, const type_7AS_NameCS &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyPost(const TYPE_AS_Name &, const TYPE_AS_BindList &, const TYPE_AS_FnBody &, const Generic &, const Generic &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyPrefixOperator(const TYPE_AS_PrefixExpr &, const type_7AS_NameCS &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifySat(const TYPE_AS_Name &, const TYPE_AS_BindList &, const TYPE_AS_BindList &, const Generic &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifySeqApplication(const TYPE_AS_Expr &, const type_FL &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
Bool vdm_GEN_uPO_pre_VerifySeqApplication(const TYPE_AS_Expr &, const type_FL &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifySeqModify(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifySeqModifyMapOverride(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifySeqOfCompatibleMaps(const type_9AS_MapletCL &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifySetOfCompatibleMaps(const TYPE_AS_Expr &, const type_7AS_NameCS &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifySubtypeOrSupertype(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyTupleBound(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyTupleBoundUnion(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_AS_Type &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
Bool vdm_GEN_uPO_pre_VerifyTupleBoundUnion(const TYPE_AS_Expr &, const TYPE_AS_Expr &, const TYPE_AS_Type &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyType(const TYPE_AS_Expr &, const TYPE_AS_Type &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_GEN_uPO_VerifyValueBinding(const TYPE_AS_Pattern &, const Generic &, const TYPE_AS_Expr &, const type_7AS_NameCS &, const TYPE_CI_ContextId &, const TYPE_POGTP_Context &);
Bool vdm_GEN_uPO_isASLiteral(const TYPE_AS_Expr &);

#endif

