//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 11-Nov-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//



#include "POG_uMEDIATOR.h"
static Sequence vdm_POG_uMEDIATOR_polst;
static Sequence vdm_POG_uMEDIATOR_status;
static Sequence vdm_POG_uMEDIATOR_typeDefs;
static Sequence vdm_POG_uMEDIATOR_fnDefs;

void TYPE_POG_uMEDIATOR_ProofObligationPP::Init(Int p1, TYPE_POG_uMEDIATOR_string p2, TYPE_POGTP_Classification p3, type_7AS_NameCL p4, TYPE_POGTP_LocContext p5, TYPE_CI_ContextId p6) {
  SetField(1, p1);
  SetField(2, p2);
  SetField(3, p3);
  SetField(4, p4);
  SetField(5, p5);
  SetField(6, p6);
}

Int TYPE_POG_uMEDIATOR_ProofObligationPP::get_no() const { return (Int) GetField(1); }

void TYPE_POG_uMEDIATOR_ProofObligationPP::set_no(const Int &p) { SetField(1, p); }

TYPE_POG_uMEDIATOR_string TYPE_POG_uMEDIATOR_ProofObligationPP::get_po() const { return (TYPE_POG_uMEDIATOR_string) GetField(2); }

void TYPE_POG_uMEDIATOR_ProofObligationPP::set_po(const TYPE_POG_uMEDIATOR_string &p) { SetField(2, p); }

TYPE_POGTP_Classification TYPE_POG_uMEDIATOR_ProofObligationPP::get_kind() const { return (TYPE_POGTP_Classification) GetField(3); }

void TYPE_POG_uMEDIATOR_ProofObligationPP::set_kind(const TYPE_POGTP_Classification &p) { SetField(3, p); }

type_7AS_NameCL TYPE_POG_uMEDIATOR_ProofObligationPP::get_source() const { return (type_7AS_NameCL) GetField(4); }

void TYPE_POG_uMEDIATOR_ProofObligationPP::set_source(const type_7AS_NameCL &p) { SetField(4, p); }

TYPE_POGTP_LocContext TYPE_POG_uMEDIATOR_ProofObligationPP::get_loc() const { return (TYPE_POGTP_LocContext) GetField(5); }

void TYPE_POG_uMEDIATOR_ProofObligationPP::set_loc(const TYPE_POGTP_LocContext &p) { SetField(5, p); }

TYPE_CI_ContextId TYPE_POG_uMEDIATOR_ProofObligationPP::get_cid() const { return (TYPE_CI_ContextId) GetField(6); }

void TYPE_POG_uMEDIATOR_ProofObligationPP::set_cid(const TYPE_CI_ContextId &p) { SetField(6, p); }

void TYPE_POG_uMEDIATOR_SPEC::Init(type_31POG_uMEDIATOR_ProofObligationPPCL p1, type_cLL p2, type_7AS_NameCL p3, type_7AS_NameCL p4) {
  SetField(1, p1);
  SetField(2, p2);
  SetField(3, p3);
  SetField(4, p4);
}

type_31POG_uMEDIATOR_ProofObligationPPCL TYPE_POG_uMEDIATOR_SPEC::get_polst() const { return (type_31POG_uMEDIATOR_ProofObligationPPCL) GetField(1); }

void TYPE_POG_uMEDIATOR_SPEC::set_polst(const type_31POG_uMEDIATOR_ProofObligationPPCL &p) { SetField(1, p); }

type_cLL TYPE_POG_uMEDIATOR_SPEC::get_status() const { return (type_cLL) GetField(2); }

void TYPE_POG_uMEDIATOR_SPEC::set_status(const type_cLL &p) { SetField(2, p); }

type_7AS_NameCL TYPE_POG_uMEDIATOR_SPEC::get_typeDefs() const { return (type_7AS_NameCL) GetField(3); }

void TYPE_POG_uMEDIATOR_SPEC::set_typeDefs(const type_7AS_NameCL &p) { SetField(3, p); }

type_7AS_NameCL TYPE_POG_uMEDIATOR_SPEC::get_fnDefs() const { return (type_7AS_NameCL) GetField(4); }

void TYPE_POG_uMEDIATOR_SPEC::set_fnDefs(const type_7AS_NameCL &p) { SetField(4, p); }

void init_POG_uMEDIATOR_VDMLib() {
  VDMGetDefaultRecInfoMap().NewTag(TAG_TYPE_POG_uMEDIATOR_ProofObligationPP, 6);
  VDMGetDefaultRecInfoMap().SetSymTag(TAG_TYPE_POG_uMEDIATOR_ProofObligationPP, "POG_uMEDIATOR`ProofObligationPP");
  VDMGetDefaultRecInfoMap().NewTag(TOKEN, 1);
  VDMGetDefaultRecInfoMap().SetSymTag(TOKEN, "token");
}
#ifdef DEF_POG_uMEDIATOR_USERIMPL

#include "POG_uMEDIATOR_userimpl.cc"

#endif


void init_POG_uMEDIATOR() { init_POG_uMEDIATOR_VDMLib(); }
#ifndef DEF_POG_uMEDIATOR_ComputePOForFnDef

type_31POG_uMEDIATOR_ProofObligationPPCL vdm_POG_uMEDIATOR_ComputePOForFnDef(const TYPE_AS_Name &vdm_POG_uMEDIATOR_name) {
  Sequence varRes_3;
  {
    Record vdm_POG_uMEDIATOR_fndef = vdm_SPEC_uAST_GetFnDef((Generic) vdm_POG_uMEDIATOR_name);
    Record vdm_POG_uMEDIATOR_contxt = vdm_POGTP_InitialContext();
    Record vdm_POG_uMEDIATOR_poglst = vdm_POG_uDEF_pog_uFnDef((Generic) vdm_POG_uMEDIATOR_fndef, (Generic) vdm_POG_uMEDIATOR_contxt);
    Sequence vdm_POG_uMEDIATOR_lst;
    if (vdm_POG_uMEDIATOR_poglst.Is(vdm_POG_uPAT_POG)) 
      vdm_POG_uMEDIATOR_lst = vdm_POG_uMEDIATOR_poglst.GetField(pos_POG_uPAT_POG_po);
    else 
      RunTime("Unknown record field selector");
    {
      Sequence res_l_13;
      Set resBind_s_15;
      Set riseq_19;
      int max_20 = (Int) vdm_POG_uMEDIATOR_lst.Length();
      for (int i_21 = 1; i_21 <= max_20; i_21++) 
        riseq_19.Insert((Int) i_21);
      resBind_s_15 = riseq_19;
      Sequence bind_l_14;
      if ((Int) resBind_s_15.Card() != (Int) 0) 
        bind_l_14 = Sort(resBind_s_15);
      bool succ_16 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_49;
      for (int i_48 = bind_l_14.First(tmpe_49); i_48; i_48 = bind_l_14.Next(tmpe_49)) {
        Int e_17 = tmpe_49;
        vdm_POG_uMEDIATOR_i = e_17;
        if (succ_16) {
          Record reselem_22(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          reselem_22 = Record(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          Int tmpVar_23;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_23 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_no);
          else 
            RunTime("Unknown record field selector");
          reselem_22.SetField(1, tmpVar_23);
          Sequence tmpVar_27;
          Record par_28;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            par_28 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_po);
          else 
            RunTime("Unknown record field selector");
          tmpVar_27 = vdm_PP_uMEDIATOR_trv_uExpr((Generic) par_28);
          reselem_22.SetField(2, tmpVar_27);
          Generic tmpVar_32;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_32 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_kind);
          else 
            RunTime("Unknown record field selector");
          reselem_22.SetField(3, tmpVar_32);
          Sequence tmpVar_36;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_36 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_source);
          else 
            RunTime("Unknown record field selector");
          reselem_22.SetField(4, tmpVar_36);
          Record tmpVar_40(vdm_POGTP_LocContext, length_POGTP_LocContext);
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_40 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_loc);
          else 
            RunTime("Unknown record field selector");
          reselem_22.SetField(5, tmpVar_40);
          Int tmpVar_44;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_44 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_cid);
          else 
            RunTime("Unknown record field selector");
          reselem_22.SetField(6, tmpVar_44);
          res_l_13.ImpAppend(reselem_22);
        }
      }
      varRes_3 = res_l_13;
    }
  }
  return (Generic) varRes_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_ComputePOForTypeDef

type_31POG_uMEDIATOR_ProofObligationPPCL vdm_POG_uMEDIATOR_ComputePOForTypeDef(const TYPE_AS_Name &vdm_POG_uMEDIATOR_name) {
  Sequence varRes_3;
  {
    Record vdm_POG_uMEDIATOR_typedef = vdm_SPEC_uAST_GetTypeDef((Generic) vdm_POG_uMEDIATOR_name);
    Record vdm_POG_uMEDIATOR_contxt = vdm_POGTP_InitialContext();
    Sequence vdm_POG_uMEDIATOR_lst = vdm_POG_uDEF_pog_uTypeDef((Generic) vdm_POG_uMEDIATOR_typedef, (Generic) vdm_POG_uMEDIATOR_contxt);
    {
      Sequence res_l_11;
      Set resBind_s_13;
      Set riseq_17;
      int max_18 = (Int) vdm_POG_uMEDIATOR_lst.Length();
      for (int i_19 = 1; i_19 <= max_18; i_19++) 
        riseq_17.Insert((Int) i_19);
      resBind_s_13 = riseq_17;
      Sequence bind_l_12;
      if ((Int) resBind_s_13.Card() != (Int) 0) 
        bind_l_12 = Sort(resBind_s_13);
      bool succ_14 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_47;
      for (int i_46 = bind_l_12.First(tmpe_47); i_46; i_46 = bind_l_12.Next(tmpe_47)) {
        Int e_15 = tmpe_47;
        vdm_POG_uMEDIATOR_i = e_15;
        if (succ_14) {
          Record reselem_20(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          reselem_20 = Record(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          Int tmpVar_21;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_21 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_no);
          else 
            RunTime("Unknown record field selector");
          reselem_20.SetField(1, tmpVar_21);
          Sequence tmpVar_25;
          Record par_26;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            par_26 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_po);
          else 
            RunTime("Unknown record field selector");
          tmpVar_25 = vdm_PP_uMEDIATOR_trv_uExpr((Generic) par_26);
          reselem_20.SetField(2, tmpVar_25);
          Generic tmpVar_30;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_30 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_kind);
          else 
            RunTime("Unknown record field selector");
          reselem_20.SetField(3, tmpVar_30);
          Sequence tmpVar_34;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_34 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_source);
          else 
            RunTime("Unknown record field selector");
          reselem_20.SetField(4, tmpVar_34);
          Record tmpVar_38(vdm_POGTP_LocContext, length_POGTP_LocContext);
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_38 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_loc);
          else 
            RunTime("Unknown record field selector");
          reselem_20.SetField(5, tmpVar_38);
          Int tmpVar_42;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_42 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_cid);
          else 
            RunTime("Unknown record field selector");
          reselem_20.SetField(6, tmpVar_42);
          res_l_11.ImpAppend(reselem_20);
        }
      }
      varRes_3 = res_l_11;
    }
  }
  return (Generic) varRes_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_ComputePOForValueDef

type_31POG_uMEDIATOR_ProofObligationPPCL vdm_POG_uMEDIATOR_ComputePOForValueDef() {
  Sequence varRes_2;
  {
    bool succ_3;
    Sequence vdm_POG_uMEDIATOR_vals = vdm_SPEC_uAST_GetValueDefSeq();
    Record vdm_POG_uMEDIATOR_contxt = vdm_POGTP_InitialContext();
    Record vdm_POG_uMEDIATOR_vals_ucontxt(vdm_POGTP_Context, length_POGTP_Context);
    Record par_8(vdm_AS_Name, length_AS_Name);
    par_8 = Record(vdm_AS_Name, length_AS_Name);
    Sequence tmpVar_9;
    tmpVar_9 = Sequence().ImpAppend(Sequence(""));
    par_8.SetField(1, tmpVar_9);
    par_8.SetField(2, vdm_CI_NilContextId);
    vdm_POG_uMEDIATOR_vals_ucontxt = vdm_POGTP_UpdateLoc((Generic) (Quote) "values", (Generic) par_8, (Generic) vdm_POG_uMEDIATOR_contxt);
    Tuple tmpVal_13(2);
    tmpVal_13 = vdm_POG_uDEF_pog_uLocalDefList((Generic) vdm_POG_uMEDIATOR_vals, (Generic) vdm_POG_uMEDIATOR_vals_ucontxt);
    Record vdm_POG_uMEDIATOR_poglst(vdm_POG_uPAT_POG, length_POG_uPAT_POG);
    succ_3 = true;
    if (tmpVal_13.IsTuple()) {
      Sequence e_l_16;
      for (int i_17 = 1; i_17 <= ((Tuple) tmpVal_13).Length(); i_17++) 
        e_l_16.ImpAppend(((Tuple) tmpVal_13).GetField(i_17));
      if (succ_3 = 2 == (Int) e_l_16.Length()) 
        vdm_POG_uMEDIATOR_poglst = (Record) e_l_16.Hd();
    }
    else 
      succ_3 = false;
    if (!succ_3) 
      RunTime("Pattern match did not succeed in value definition");
    Sequence vdm_POG_uMEDIATOR_lst;
    if (vdm_POG_uMEDIATOR_poglst.Is(vdm_POG_uPAT_POG)) 
      vdm_POG_uMEDIATOR_lst = vdm_POG_uMEDIATOR_poglst.GetField(pos_POG_uPAT_POG_po);
    else 
      RunTime("Unknown record field selector");
    {
      Sequence res_l_20;
      Set resBind_s_22;
      Set riseq_26;
      int max_27 = (Int) vdm_POG_uMEDIATOR_lst.Length();
      for (int i_28 = 1; i_28 <= max_27; i_28++) 
        riseq_26.Insert((Int) i_28);
      resBind_s_22 = riseq_26;
      Sequence bind_l_21;
      if ((Int) resBind_s_22.Card() != (Int) 0) 
        bind_l_21 = Sort(resBind_s_22);
      bool succ_23 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_56;
      for (int i_55 = bind_l_21.First(tmpe_56); i_55; i_55 = bind_l_21.Next(tmpe_56)) {
        Int e_24 = tmpe_56;
        vdm_POG_uMEDIATOR_i = e_24;
        if (succ_23) {
          Record reselem_29(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          reselem_29 = Record(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          Int tmpVar_30;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_30 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_no);
          else 
            RunTime("Unknown record field selector");
          reselem_29.SetField(1, tmpVar_30);
          Sequence tmpVar_34;
          Record par_35;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            par_35 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_po);
          else 
            RunTime("Unknown record field selector");
          tmpVar_34 = vdm_PP_uMEDIATOR_trv_uExpr((Generic) par_35);
          reselem_29.SetField(2, tmpVar_34);
          Generic tmpVar_39;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_39 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_kind);
          else 
            RunTime("Unknown record field selector");
          reselem_29.SetField(3, tmpVar_39);
          Sequence tmpVar_43;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_43 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_source);
          else 
            RunTime("Unknown record field selector");
          reselem_29.SetField(4, tmpVar_43);
          Record tmpVar_47(vdm_POGTP_LocContext, length_POGTP_LocContext);
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_47 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_loc);
          else 
            RunTime("Unknown record field selector");
          reselem_29.SetField(5, tmpVar_47);
          Int tmpVar_51;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_51 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_cid);
          else 
            RunTime("Unknown record field selector");
          reselem_29.SetField(6, tmpVar_51);
          res_l_20.ImpAppend(reselem_29);
        }
      }
      varRes_2 = res_l_20;
    }
  }
  return (Generic) varRes_2;
}
#endif

#ifndef DEF_POG_uMEDIATOR_ComputePOs

type_31POG_uMEDIATOR_ProofObligationPPCL vdm_POG_uMEDIATOR_ComputePOs(const TYPE_AS_AstCI &vdm_POG_uMEDIATOR_astci) {
  Sequence varRes_3;
  {
    Sequence vdm_POG_uMEDIATOR_lst = vdm_POG_uDEF_pog_uAstCI((Generic) vdm_POG_uMEDIATOR_astci);
    {
      Sequence res_l_7;
      Set resBind_s_9;
      Set riseq_13;
      int max_14 = (Int) vdm_POG_uMEDIATOR_lst.Length();
      for (int i_15 = 1; i_15 <= max_14; i_15++) 
        riseq_13.Insert((Int) i_15);
      resBind_s_9 = riseq_13;
      Sequence bind_l_8;
      if ((Int) resBind_s_9.Card() != (Int) 0) 
        bind_l_8 = Sort(resBind_s_9);
      bool succ_10 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_43;
      for (int i_42 = bind_l_8.First(tmpe_43); i_42; i_42 = bind_l_8.Next(tmpe_43)) {
        Int e_11 = tmpe_43;
        vdm_POG_uMEDIATOR_i = e_11;
        if (succ_10) {
          Record reselem_16(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          reselem_16 = Record(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          Int tmpVar_17;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_17 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_no);
          else 
            RunTime("Unknown record field selector");
          reselem_16.SetField(1, tmpVar_17);
          Sequence tmpVar_21;
          Record par_22;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            par_22 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_po);
          else 
            RunTime("Unknown record field selector");
          tmpVar_21 = vdm_PP_uMEDIATOR_trv_uExpr((Generic) par_22);
          reselem_16.SetField(2, tmpVar_21);
          Generic tmpVar_26;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_26 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_kind);
          else 
            RunTime("Unknown record field selector");
          reselem_16.SetField(3, tmpVar_26);
          Sequence tmpVar_30;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_30 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_source);
          else 
            RunTime("Unknown record field selector");
          reselem_16.SetField(4, tmpVar_30);
          Record tmpVar_34(vdm_POGTP_LocContext, length_POGTP_LocContext);
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_34 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_loc);
          else 
            RunTime("Unknown record field selector");
          reselem_16.SetField(5, tmpVar_34);
          Int tmpVar_38;
          if (((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POGTP_ProofObligation)) 
            tmpVar_38 = ((Record) vdm_POG_uMEDIATOR_lst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POGTP_ProofObligation_cid);
          else 
            RunTime("Unknown record field selector");
          reselem_16.SetField(6, tmpVar_38);
          res_l_7.ImpAppend(reselem_16);
        }
      }
      varRes_3 = res_l_7;
    }
  }
  return (Generic) varRes_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_ComputePrettyPOs

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_ComputePrettyPOs(const type_31POG_uMEDIATOR_ProofObligationPPCL &vdm_POG_uMEDIATOR_polst) {
  Sequence varRes_3;
  Sequence par_5;
  {
    Sequence res_l_6;
    Set resBind_s_8;
    Set riseq_12;
    int max_13 = (Int) vdm_POG_uMEDIATOR_polst.Length();
    for (int i_14 = 1; i_14 <= max_13; i_14++) 
      riseq_12.Insert((Int) i_14);
    resBind_s_8 = riseq_12;
    Sequence bind_l_7;
    if ((Int) resBind_s_8.Card() != (Int) 0) 
      bind_l_7 = Sort(resBind_s_8);
    bool succ_9 = true;
    Int vdm_POG_uMEDIATOR_i;
    Generic tmpe_85;
    for (int i_84 = bind_l_7.First(tmpe_85); i_84; i_84 = bind_l_7.Next(tmpe_85)) {
      Int e_10 = tmpe_85;
      vdm_POG_uMEDIATOR_i = e_10;
      if (succ_9) {
        Sequence reselem_15;
        {
          Sequence vdm_POG_uMEDIATOR_number;
          Sequence var1_18;
          Sequence var2_20;
          Int par_21;
          if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
            par_21 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_no);
          else 
            RunTime("Unknown record field selector");
          var2_20 = vdm_POG_uMEDIATOR_Nat2str((Generic) par_21);
          var1_18.ImpConc(Sequence("Proof Obligation #")).ImpConc(var2_20);
          vdm_POG_uMEDIATOR_number.ImpConc(var1_18).ImpConc(Sequence(" :\n"));
          Sequence vdm_POG_uMEDIATOR_explain;
          Sequence var1_27;
          Sequence var1_28;
          Sequence var1_29;
          Sequence var1_30;
          Sequence var1_31;
          Sequence var2_33;
          Record par_34(vdm_POGTP_LocContext, length_POGTP_LocContext);
          if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
            par_34 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_loc);
          else 
            RunTime("Unknown record field selector");
          var2_33 = vdm_PP_uMEDIATOR_PrintPOLocContext((Generic) par_34);
          var1_31.ImpConc(Sequence("In ")).ImpConc(var2_33);
          var1_30.ImpConc(var1_31).ImpConc(Sequence(", "));
          Sequence var2_39;
          Int par_40;
          if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
            par_40 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_cid);
          else 
            RunTime("Unknown record field selector");
          var2_39 = vdm_PP_uMEDIATOR_PrintPOLocation((Generic) par_40);
          var1_29.ImpConc(var1_30).ImpConc(var2_39);
          var1_28.ImpConc(var1_29).ImpConc(Sequence(": "));
          Sequence var2_45;
          Generic par_46;
          if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
            par_46 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_kind);
          else 
            RunTime("Unknown record field selector");
          Sequence par_50;
          if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
            par_50 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_source);
          else 
            RunTime("Unknown record field selector");
          var2_45 = vdm_PP_uMEDIATOR_PrintPODueTo((Generic) par_46, (Generic) par_50);
          var1_27.ImpConc(var1_28).ImpConc(var2_45);
          vdm_POG_uMEDIATOR_explain.ImpConc(var1_27).ImpConc(Sequence("\n"));
          Sequence vdm_POG_uMEDIATOR_line;
          Sequence unArg_56;
          {
            Sequence res_l_57;
            Set resBind_s_59;
            Set riseq_63;
            int max_64 = (Int) vdm_POG_uMEDIATOR_explain.Length();
            for (int i_65 = 1; i_65 <= max_64; i_65++) 
              riseq_63.Insert((Int) i_65);
            resBind_s_59 = riseq_63;
            Sequence bind_l_58;
            if ((Int) resBind_s_59.Card() != (Int) 0) 
              bind_l_58 = Sort(resBind_s_59);
            bool succ_60 = true;
            Int vdm_POG_uMEDIATOR_i;
            Generic tmpe_68;
            for (int i_67 = bind_l_58.First(tmpe_68); i_67; i_67 = bind_l_58.Next(tmpe_68)) {
              Int e_61 = tmpe_68;
              vdm_POG_uMEDIATOR_i = e_61;
              if (succ_60) 
                res_l_57.ImpAppend(Sequence("-"));
            }
            unArg_56 = res_l_57;
          }
          Sequence rdcseq_69;          Generic tmpe_72;          for (int i_71 = unArg_56.First(tmpe_72); i_71; i_71 = unArg_56.Next(tmpe_72)) {
            Sequence e_70 = tmpe_72;
            rdcseq_69.ImpConc(e_70);
          }          vdm_POG_uMEDIATOR_line = rdcseq_69;
          Sequence var1_73;
          Sequence var1_74;
          Sequence var1_75;
          var1_75.ImpConc(vdm_POG_uMEDIATOR_number).ImpConc(vdm_POG_uMEDIATOR_explain);
          var1_74.ImpConc(var1_75).ImpConc(vdm_POG_uMEDIATOR_line);
          var1_73.ImpConc(var1_74).ImpConc(Sequence("\n"));
          Sequence var2_80;
          if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
            var2_80 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_po);
          else 
            RunTime("Unknown record field selector");
          reselem_15.ImpConc(var1_73).ImpConc(var2_80);
        }
        res_l_6.ImpAppend(reselem_15);
      }
    }
    par_5 = res_l_6;
  }
  varRes_3 = vdm_POG_uMEDIATOR_List2SeparatorList((Generic) Sequence("\n\n"), (Generic) par_5);
  return (Generic) varRes_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_List2SeparatorList

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_List2SeparatorList(const TYPE_POG_uMEDIATOR_string &vdm_POG_uMEDIATOR_separator, const type_cLL &vdm_POG_uMEDIATOR_ss) {
  Sequence varRes_4;
  if (((Bool) (vdm_POG_uMEDIATOR_ss == Sequence())).GetValue()) 
    varRes_4 = Sequence("");
  else {
    Sequence vdm_POG_uMEDIATOR_head = (Sequence) vdm_POG_uMEDIATOR_ss.Hd();
    Sequence vdm_POG_uMEDIATOR_tail;
    if (((Bool) (vdm_POG_uMEDIATOR_ss.Tl() == Sequence())).GetValue()) 
      vdm_POG_uMEDIATOR_tail = Sequence("");
    else 
      vdm_POG_uMEDIATOR_tail.ImpConc(vdm_POG_uMEDIATOR_separator).ImpConc(vdm_POG_uMEDIATOR_List2SeparatorList((Generic) vdm_POG_uMEDIATOR_separator, (Generic) vdm_POG_uMEDIATOR_ss.Tl()));
    varRes_4.ImpConc(vdm_POG_uMEDIATOR_head).ImpConc(vdm_POG_uMEDIATOR_tail);
  }
  return (Generic) varRes_4;
}
#endif

#ifndef DEF_POG_uMEDIATOR_Nat2str

type_cL vdm_POG_uMEDIATOR_Nat2str(const Int &vdm_POG_uMEDIATOR_n) {
  Sequence varRes_3;
  {
    Int vdm_POG_uMEDIATOR_d = (Int) (vdm_POG_uMEDIATOR_n / (Int) 10);
    Int vdm_POG_uMEDIATOR_r = vdm_POG_uMEDIATOR_n - (Int) 10 * vdm_POG_uMEDIATOR_d;
    Sequence vdm_POG_uMEDIATOR_r_ustr;
    bool succ_14 = true;
    {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 0) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("0");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 1) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("1");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 2) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("2");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 3) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("3");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 4) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("4");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 5) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("5");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 6) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("6");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 7) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("7");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 8) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("8");
    }
    if (!succ_14) {
      succ_14 = true;
      if (vdm_POG_uMEDIATOR_r != (Int) 9) 
        succ_14 = false;
      if (succ_14) 
        vdm_POG_uMEDIATOR_r_ustr = Sequence("9");
    }
    if (!succ_14) 
      RunTime("No \'others\' branch in CasesExpr");
    Sequence vdm_POG_uMEDIATOR_d_ustr;
    if (((Bool) (vdm_POG_uMEDIATOR_d == (Int) 0)).GetValue()) 
      vdm_POG_uMEDIATOR_d_ustr = Sequence("");
    else 
      vdm_POG_uMEDIATOR_d_ustr = vdm_POG_uMEDIATOR_Nat2str((Generic) vdm_POG_uMEDIATOR_d);
    varRes_3.ImpConc(vdm_POG_uMEDIATOR_d_ustr).ImpConc(vdm_POG_uMEDIATOR_r_ustr);
  }
  return (Generic) varRes_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pp_uProofObligationAsVdmFunction

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_pp_uProofObligationAsVdmFunction(const TYPE_POG_uMEDIATOR_ProofObligationPP &var_1_1) {
  Int vdm_POG_uMEDIATOR_cid;
  Generic vdm_POG_uMEDIATOR_kind;
  Record vdm_POG_uMEDIATOR_loc(vdm_POGTP_LocContext, length_POGTP_LocContext);
  Int vdm_POG_uMEDIATOR_no;
  Sequence vdm_POG_uMEDIATOR_po;
  Sequence vdm_POG_uMEDIATOR_source;
  bool succ_2 = true;
  if (var_1_1.IsRecord() && vdm_POG_uMEDIATOR_ProofObligationPP == var_1_1.GetTag()) {
    Sequence e_l_45;
    for (int i_46 = 1; i_46 <= var_1_1.Length(); i_46++) 
      e_l_45.ImpAppend(var_1_1.GetField(i_46));
    if (succ_2 = 6 == (Int) e_l_45.Length()) {
      vdm_POG_uMEDIATOR_no = (Generic) e_l_45.Hd();
      vdm_POG_uMEDIATOR_po = (Generic) e_l_45[2];
      vdm_POG_uMEDIATOR_kind = (Generic) e_l_45[3];
      vdm_POG_uMEDIATOR_source = (Generic) e_l_45[4];
      vdm_POG_uMEDIATOR_loc = (Generic) e_l_45[5];
      vdm_POG_uMEDIATOR_cid = (Generic) e_l_45[6];
    }
  }
  else 
    succ_2 = false;
  if (!succ_2) 
    RunTime("Pattern Match in Function Apply in function : pp_uProofObligationAsVdmFunction failed");
  Sequence varRes_3;
  Sequence var1_4;
  Sequence var1_5;
  Sequence var1_6;
  Sequence var1_7;
  Sequence var1_8;
  Sequence var1_9;
  Sequence var1_10;
  Sequence var1_11;
  Sequence var1_12;
  Sequence var1_13;
  Sequence var1_14;
  Sequence var1_15;
  Sequence var1_16;
  Sequence var1_17;
  Sequence var1_18;
  Sequence var1_19;
  var1_19.ImpConc(Sequence("-- Proof Obligation #")).ImpConc(vdm_POG_uMEDIATOR_Nat2str((Generic) vdm_POG_uMEDIATOR_no));
  var1_18.ImpConc(var1_19).ImpConc(Sequence(" : "));
  var1_17.ImpConc(var1_18).ImpConc(Sequence("In "));
  var1_16.ImpConc(var1_17).ImpConc(vdm_PP_uMEDIATOR_PrintPOLocContext((Generic) vdm_POG_uMEDIATOR_loc));
  var1_15.ImpConc(var1_16).ImpConc(Sequence(" "));
  var1_14.ImpConc(var1_15).ImpConc(Sequence("verifying "));
  var1_13.ImpConc(var1_14).ImpConc(vdm_PP_uMEDIATOR_PrintPODueTo((Generic) vdm_POG_uMEDIATOR_kind, (Generic) vdm_POG_uMEDIATOR_source));
  var1_12.ImpConc(var1_13).ImpConc(Sequence("; "));
  var1_11.ImpConc(var1_12).ImpConc(vdm_PP_uMEDIATOR_PrintPOLocation((Generic) vdm_POG_uMEDIATOR_cid));
  var1_10.ImpConc(var1_11).ImpConc(Sequence("\n"));
  var1_9.ImpConc(var1_10).ImpConc(Sequence("PO"));
  var1_8.ImpConc(var1_9).ImpConc(vdm_POG_uMEDIATOR_Nat2str((Generic) vdm_POG_uMEDIATOR_no));
  var1_7.ImpConc(var1_8).ImpConc(Sequence(" : () -> bool\n"));
  var1_6.ImpConc(var1_7).ImpConc(Sequence("PO"));
  var1_5.ImpConc(var1_6).ImpConc(vdm_POG_uMEDIATOR_Nat2str((Generic) vdm_POG_uMEDIATOR_no));
  var1_4.ImpConc(var1_5).ImpConc(Sequence(" () ==\n"));
  varRes_3.ImpConc(var1_4).ImpConc(vdm_POG_uMEDIATOR_po);
  return (Generic) varRes_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_GenPO

void vdm_POG_uMEDIATOR_GenPO() {
  Sequence rhs_2;
  Record par_3(vdm_AS_AstCI, length_AS_AstCI);
  par_3 = Record(vdm_AS_AstCI, length_AS_AstCI);
  Sequence tmpVar_4;
  tmpVar_4 = Sequence().ImpAppend(vdm_SPEC_uAST_GetAst());
  par_3.SetField(1, tmpVar_4);
  par_3.SetField(2, Sequence());
  par_3.SetField(3, Map());
  rhs_2 = vdm_POG_uMEDIATOR_ComputePOs((Generic) par_3);
  vdm_POG_uMEDIATOR_polst = rhs_2;
  Sequence rhs_8;
  {
    Sequence res_l_9;
    Set resBind_s_11;
    Set riseq_15;
    int max_16 = (Int) vdm_POG_uMEDIATOR_polst.Length();
    for (int i_17 = 1; i_17 <= max_16; i_17++) 
      riseq_15.Insert((Int) i_17);
    resBind_s_11 = riseq_15;
    Sequence bind_l_10;
    if ((Int) resBind_s_11.Card() != (Int) 0) 
      bind_l_10 = Sort(resBind_s_11);
    bool succ_12 = true;
    Int vdm_POG_uMEDIATOR_i;
    Generic tmpe_20;
    for (int i_19 = bind_l_10.First(tmpe_20); i_19; i_19 = bind_l_10.Next(tmpe_20)) {
      Int e_13 = tmpe_20;
      vdm_POG_uMEDIATOR_i = e_13;
      if (succ_12) 
        res_l_9.ImpAppend(Sequence("New"));
    }
    rhs_8 = res_l_9;
  }
  vdm_POG_uMEDIATOR_status = rhs_8;
}
#endif

#ifndef DEF_POG_uMEDIATOR_GenPOForFnDef

void vdm_POG_uMEDIATOR_GenPOForFnDef(const Int &vdm_POG_uMEDIATOR_index) {
  Sequence vdm_POG_uMEDIATOR_fnpos = vdm_POG_uMEDIATOR_ComputePOForFnDef((Generic) (Record) vdm_POG_uMEDIATOR_fnDefs[vdm_POG_uMEDIATOR_index.GetValue()]);
  {
    Sequence rhs_8;
    rhs_8.ImpConc(vdm_POG_uMEDIATOR_polst).ImpConc(vdm_POG_uMEDIATOR_fnpos);
    vdm_POG_uMEDIATOR_polst = rhs_8;
    Sequence rhs_11;
    Sequence var2_13;
    {
      Sequence res_l_14;
      Set resBind_s_16;
      Set riseq_20;
      int max_21 = (Int) vdm_POG_uMEDIATOR_fnpos.Length();
      for (int i_22 = 1; i_22 <= max_21; i_22++) 
        riseq_20.Insert((Int) i_22);
      resBind_s_16 = riseq_20;
      Sequence bind_l_15;
      if ((Int) resBind_s_16.Card() != (Int) 0) 
        bind_l_15 = Sort(resBind_s_16);
      bool succ_17 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_25;
      for (int i_24 = bind_l_15.First(tmpe_25); i_24; i_24 = bind_l_15.Next(tmpe_25)) {
        Int e_18 = tmpe_25;
        vdm_POG_uMEDIATOR_i = e_18;
        if (succ_17) 
          res_l_14.ImpAppend(Sequence("New"));
      }
      var2_13 = res_l_14;
    }
    rhs_11.ImpConc(vdm_POG_uMEDIATOR_status).ImpConc(var2_13);
    vdm_POG_uMEDIATOR_status = rhs_11;
  }
}
#endif

#ifndef DEF_POG_uMEDIATOR_GenPOForTypeDef

void vdm_POG_uMEDIATOR_GenPOForTypeDef(const Int &vdm_POG_uMEDIATOR_index) {
  Sequence vdm_POG_uMEDIATOR_tppos = vdm_POG_uMEDIATOR_ComputePOForTypeDef((Generic) (Record) vdm_POG_uMEDIATOR_typeDefs[vdm_POG_uMEDIATOR_index.GetValue()]);
  {
    Sequence rhs_8;
    rhs_8.ImpConc(vdm_POG_uMEDIATOR_polst).ImpConc(vdm_POG_uMEDIATOR_tppos);
    vdm_POG_uMEDIATOR_polst = rhs_8;
    Sequence rhs_11;
    Sequence var2_13;
    {
      Sequence res_l_14;
      Set resBind_s_16;
      Set riseq_20;
      int max_21 = (Int) vdm_POG_uMEDIATOR_tppos.Length();
      for (int i_22 = 1; i_22 <= max_21; i_22++) 
        riseq_20.Insert((Int) i_22);
      resBind_s_16 = riseq_20;
      Sequence bind_l_15;
      if ((Int) resBind_s_16.Card() != (Int) 0) 
        bind_l_15 = Sort(resBind_s_16);
      bool succ_17 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_25;
      for (int i_24 = bind_l_15.First(tmpe_25); i_24; i_24 = bind_l_15.Next(tmpe_25)) {
        Int e_18 = tmpe_25;
        vdm_POG_uMEDIATOR_i = e_18;
        if (succ_17) 
          res_l_14.ImpAppend(Sequence("New"));
      }
      var2_13 = res_l_14;
    }
    rhs_11.ImpConc(vdm_POG_uMEDIATOR_status).ImpConc(var2_13);
    vdm_POG_uMEDIATOR_status = rhs_11;
  }
}
#endif

#ifndef DEF_POG_uMEDIATOR_GenPOForValueDef

void vdm_POG_uMEDIATOR_GenPOForValueDef() {
  Sequence vdm_POG_uMEDIATOR_valpos = vdm_POG_uMEDIATOR_ComputePOForValueDef();
  {
    Sequence rhs_4;
    rhs_4.ImpConc(vdm_POG_uMEDIATOR_polst).ImpConc(vdm_POG_uMEDIATOR_valpos);
    vdm_POG_uMEDIATOR_polst = rhs_4;
    Sequence rhs_7;
    Sequence var2_9;
    {
      Sequence res_l_10;
      Set resBind_s_12;
      Set riseq_16;
      int max_17 = (Int) vdm_POG_uMEDIATOR_valpos.Length();
      for (int i_18 = 1; i_18 <= max_17; i_18++) 
        riseq_16.Insert((Int) i_18);
      resBind_s_12 = riseq_16;
      Sequence bind_l_11;
      if ((Int) resBind_s_12.Card() != (Int) 0) 
        bind_l_11 = Sort(resBind_s_12);
      bool succ_13 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_21;
      for (int i_20 = bind_l_11.First(tmpe_21); i_20; i_20 = bind_l_11.Next(tmpe_21)) {
        Int e_14 = tmpe_21;
        vdm_POG_uMEDIATOR_i = e_14;
        if (succ_13) 
          res_l_10.ImpAppend(Sequence("New"));
      }
      var2_9 = res_l_10;
    }
    rhs_7.ImpConc(vdm_POG_uMEDIATOR_status).ImpConc(var2_9);
    vdm_POG_uMEDIATOR_status = rhs_7;
    Sequence rhs_22;
    {
      Sequence res_l_23;
      Set resBind_s_25;
      Set riseq_29;
      int max_30 = (Int) vdm_POG_uMEDIATOR_polst.Length();
      for (int i_31 = 1; i_31 <= max_30; i_31++) 
        riseq_29.Insert((Int) i_31);
      resBind_s_25 = riseq_29;
      Sequence bind_l_24;
      if ((Int) resBind_s_25.Card() != (Int) 0) 
        bind_l_24 = Sort(resBind_s_25);
      bool succ_26 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_40;
      for (int i_39 = bind_l_24.First(tmpe_40); i_39; i_39 = bind_l_24.Next(tmpe_40)) {
        Int e_27 = tmpe_40;
        vdm_POG_uMEDIATOR_i = e_27;
        if (succ_26) {
          Record reselem_32(vdm_POG_uMEDIATOR_ProofObligationPP, length_POG_uMEDIATOR_ProofObligationPP);
          Record tmpRE_36 = (Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()];
          int mu_37;
          mu_37 = pos_POG_uMEDIATOR_ProofObligationPP_no;
          tmpRE_36.SetField(mu_37, vdm_POG_uMEDIATOR_i);
          reselem_32 = tmpRE_36;
          res_l_23.ImpAppend(reselem_32);
        }
      }
      rhs_22 = res_l_23;
    }
    vdm_POG_uMEDIATOR_polst = rhs_22;
  }
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetNumberOfPO

Int vdm_POG_uMEDIATOR_GetNumberOfPO() { return (Generic) (Int) vdm_POG_uMEDIATOR_polst.Length(); }
#endif

#ifndef DEF_POG_uMEDIATOR_GetPO

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GetPO(const Int &vdm_POG_uMEDIATOR_i) {
  Sequence rexpr_3;
  Sequence var1_4;
  Sequence var1_5;
  Sequence var2_7;
  Int par_8;
  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    par_8 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_no);
  else 
    RunTime("Unknown record field selector");
  var2_7 = vdm_POG_uMEDIATOR_Nat2str((Generic) par_8);
  var1_5.ImpConc(Sequence("Proof Obligation #")).ImpConc(var2_7);
  var1_4.ImpConc(var1_5).ImpConc(Sequence(" :\n"));
  Sequence var2_13;
  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    var2_13 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_po);
  else 
    RunTime("Unknown record field selector");
  rexpr_3.ImpConc(var1_4).ImpConc(var2_13);
  return (Generic) rexpr_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPO

Bool vdm_POG_uMEDIATOR_pre_GetPO(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_i;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_i = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPO failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_i.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_polst.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPOClassification

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GetPOClassification(const Int &vdm_POG_uMEDIATOR_index) {
  Sequence rexpr_3;
  Generic par_4;
  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    par_4 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_kind);
  else 
    RunTime("Unknown record field selector");
  rexpr_3 = vdm_PP_uMEDIATOR_PrintPOKind((Generic) par_4);
  return (Generic) rexpr_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPOClassification

Bool vdm_POG_uMEDIATOR_pre_GetPOClassification(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_index;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_index = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPOClassification failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_index.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_polst.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPOCol

Int vdm_POG_uMEDIATOR_GetPOCol(const Int &vdm_POG_uMEDIATOR_index) {
  bool succ_3;
  Tuple tmpVal_4(2);
  Int par_5;  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    par_5 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_cid);
  else 
    RunTime("Unknown record field selector");  tmpVal_4 = vdm_CI_GetLocation((Generic) par_5);
  Int vdm_POG_uMEDIATOR_col;
  succ_3 = true;
  if (tmpVal_4.IsTuple()) {
    Sequence e_l_9;
    for (int i_10 = 1; i_10 <= ((Tuple) tmpVal_4).Length(); i_10++) 
      e_l_9.ImpAppend(((Tuple) tmpVal_4).GetField(i_10));
    if (succ_3 = 2 == (Int) e_l_9.Length()) 
      vdm_POG_uMEDIATOR_col = (Int) e_l_9[2];
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern match did not succeed in value definition");
  return (Generic) vdm_POG_uMEDIATOR_col;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPOCol

Bool vdm_POG_uMEDIATOR_pre_GetPOCol(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_index;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_index = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPOCol failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_index.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_polst.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPODueTo

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GetPODueTo(const Int &vdm_POG_uMEDIATOR_index) {
  Sequence rexpr_3;
  Generic par_4;
  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    par_4 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_kind);
  else 
    RunTime("Unknown record field selector");
  Sequence par_8;
  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    par_8 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_source);
  else 
    RunTime("Unknown record field selector");
  rexpr_3 = vdm_PP_uMEDIATOR_PrintPODueTo((Generic) par_4, (Generic) par_8);
  return (Generic) rexpr_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPODueTo

Bool vdm_POG_uMEDIATOR_pre_GetPODueTo(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_index;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_index = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPODueTo failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_index.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_polst.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPOLine

Int vdm_POG_uMEDIATOR_GetPOLine(const Int &vdm_POG_uMEDIATOR_index) {
  bool succ_3;
  Tuple tmpVal_4(2);
  Int par_5;  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    par_5 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_cid);
  else 
    RunTime("Unknown record field selector");  tmpVal_4 = vdm_CI_GetLocation((Generic) par_5);
  Int vdm_POG_uMEDIATOR_line;
  succ_3 = true;
  if (tmpVal_4.IsTuple()) {
    Sequence e_l_9;
    for (int i_10 = 1; i_10 <= ((Tuple) tmpVal_4).Length(); i_10++) 
      e_l_9.ImpAppend(((Tuple) tmpVal_4).GetField(i_10));
    if (succ_3 = 2 == (Int) e_l_9.Length()) 
      vdm_POG_uMEDIATOR_line = (Int) e_l_9.Hd();
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern match did not succeed in value definition");
  return (Generic) vdm_POG_uMEDIATOR_line;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPOLine

Bool vdm_POG_uMEDIATOR_pre_GetPOLine(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_index;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_index = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPOLine failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_index.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_polst.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPOLocClassification

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GetPOLocClassification(const Int &vdm_POG_uMEDIATOR_index) {
  Sequence rexpr_3;
  Record par_4(vdm_POGTP_LocContext, length_POGTP_LocContext);
  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    par_4 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_loc);
  else 
    RunTime("Unknown record field selector");
  rexpr_3 = vdm_PP_uMEDIATOR_PrintPOLocContext((Generic) par_4);
  return (Generic) rexpr_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPOLocClassification

Bool vdm_POG_uMEDIATOR_pre_GetPOLocClassification(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_index;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_index = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPOLocClassification failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_index.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_polst.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPOLocation

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GetPOLocation(const Int &vdm_POG_uMEDIATOR_index) {
  Sequence rexpr_3;
  Int par_4;
  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    par_4 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_cid);
  else 
    RunTime("Unknown record field selector");
  rexpr_3 = vdm_PP_uMEDIATOR_PrintPOLocation((Generic) par_4);
  return (Generic) rexpr_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPOLocation

Bool vdm_POG_uMEDIATOR_pre_GetPOLocation(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_index;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_index = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPOLocation failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_index.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_polst.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPOName

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GetPOName(const Int &vdm_POG_uMEDIATOR_index) {
  Sequence rexpr_3;
  Record par_4(vdm_AS_Name, length_AS_Name);
  Record tmpRec_5(vdm_POGTP_LocContext, length_POGTP_LocContext);
  if (((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).Is(vdm_POG_uMEDIATOR_ProofObligationPP)) 
    tmpRec_5 = ((Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_index.GetValue()]).GetField(pos_POG_uMEDIATOR_ProofObligationPP_loc);
  else 
    RunTime("Unknown record field selector");
  if (tmpRec_5.Is(vdm_POGTP_LocContext)) 
    par_4 = tmpRec_5.GetField(pos_POGTP_LocContext_name);
  else 
    RunTime("Unknown record field selector");
  rexpr_3 = vdm_PP_uMEDIATOR_PrintName((Generic) par_4);
  return (Generic) rexpr_3;
}
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPOName

Bool vdm_POG_uMEDIATOR_pre_GetPOName(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_index;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_index = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPOName failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_index.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_polst.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPOStatus

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GetPOStatus(const Int &vdm_POG_uMEDIATOR_index) { return (Generic) (Sequence) vdm_POG_uMEDIATOR_status[vdm_POG_uMEDIATOR_index.GetValue()]; }
#endif

#ifndef DEF_POG_uMEDIATOR_pre_GetPOStatus

Bool vdm_POG_uMEDIATOR_pre_GetPOStatus(const Int &var_1_1, const TYPE_POG_uMEDIATOR_SPEC &var_2_2) {
  Sequence vdm_POG_uMEDIATOR_fnDefs;
  Int vdm_POG_uMEDIATOR_index;
  Sequence vdm_POG_uMEDIATOR_polst;
  Sequence vdm_POG_uMEDIATOR_status;
  Sequence vdm_POG_uMEDIATOR_typeDefs;
  bool succ_3 = true;
  vdm_POG_uMEDIATOR_index = var_1_1;
  if (var_2_2.IsRecord() && vdm_POG_uMEDIATOR_SPEC == var_2_2.GetTag()) {
    Sequence e_l_8;
    for (int i_9 = 1; i_9 <= var_2_2.Length(); i_9++) 
      e_l_8.ImpAppend(var_2_2.GetField(i_9));
    if (succ_3 = 4 == (Int) e_l_8.Length()) {
      vdm_POG_uMEDIATOR_polst = (Sequence) e_l_8.Hd();
      vdm_POG_uMEDIATOR_status = (Sequence) e_l_8[2];
      vdm_POG_uMEDIATOR_typeDefs = (Sequence) e_l_8[3];
      vdm_POG_uMEDIATOR_fnDefs = (Sequence) e_l_8[4];
    }
  }
  else 
    succ_3 = false;
  if (!succ_3) 
    RunTime("Pattern Match in Function Apply in function : pre_GetPOStatus failed");
  return (Generic) (Bool) ((vdm_POG_uMEDIATOR_index.GetValue()) <= (((Int) vdm_POG_uMEDIATOR_status.Length()).GetValue()));
}
#endif

#ifndef DEF_POG_uMEDIATOR_GetPrettyPO

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GetPrettyPO() { return (Generic) vdm_POG_uMEDIATOR_ComputePrettyPOs((Generic) vdm_POG_uMEDIATOR_polst); }
#endif

#ifndef DEF_POG_uMEDIATOR_GlueSpecWithPoLst

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_GlueSpecWithPoLst() {
  Sequence rexpr_2;
  {
    Sequence vdm_POG_uMEDIATOR_mod_uname = vdm_PP_uMEDIATOR_trv_uNameName((Generic) vdm_SPEC_uAST_GetModuleName());
    Sequence vdm_POG_uMEDIATOR_pp_umod = vdm_PP_uMEDIATOR_trv_uDefinitions();
    Sequence vdm_POG_uMEDIATOR_pp_upo;
    Sequence par_9;
    {
      Sequence res_l_10;
      Set resBind_s_12;
      Set riseq_16;
      int max_17 = (Int) vdm_POG_uMEDIATOR_polst.Length();
      for (int i_18 = 1; i_18 <= max_17; i_18++) 
        riseq_16.Insert((Int) i_18);
      resBind_s_12 = riseq_16;
      Sequence bind_l_11;
      if ((Int) resBind_s_12.Card() != (Int) 0) 
        bind_l_11 = Sort(resBind_s_12);
      bool succ_13 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_24;
      for (int i_23 = bind_l_11.First(tmpe_24); i_23; i_23 = bind_l_11.Next(tmpe_24)) {
        Int e_14 = tmpe_24;
        vdm_POG_uMEDIATOR_i = e_14;
        if (succ_13) 
          res_l_10.ImpAppend(vdm_POG_uMEDIATOR_pp_uProofObligationAsVdmFunction((Generic) (Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]));
      }
      par_9 = res_l_10;
    }
    vdm_POG_uMEDIATOR_pp_upo = vdm_POG_uMEDIATOR_List2SeparatorList((Generic) Sequence(";\n\n"), (Generic) par_9);
    Sequence var1_25;
    Sequence var1_26;
    Sequence var1_27;
    Sequence var1_28;
    Sequence var1_29;
    Sequence var1_30;
    Sequence var1_31;
    Sequence var1_32;
    var1_32.ImpConc(Sequence("module ")).ImpConc(vdm_POG_uMEDIATOR_mod_uname);
    var1_31.ImpConc(var1_32).ImpConc(Sequence("\n\n"));
    var1_30.ImpConc(var1_31).ImpConc(Sequence("definitions\n\n"));
    var1_29.ImpConc(var1_30).ImpConc(vdm_POG_uMEDIATOR_pp_umod);
    var1_28.ImpConc(var1_29).ImpConc(Sequence("\n\nfunctions\n\n"));
    var1_27.ImpConc(var1_28).ImpConc(vdm_POG_uMEDIATOR_pp_upo);
    var1_26.ImpConc(var1_27).ImpConc(Sequence("\n\nend "));
    var1_25.ImpConc(var1_26).ImpConc(vdm_POG_uMEDIATOR_mod_uname);
    rexpr_2.ImpConc(var1_25).ImpConc(Sequence("\n"));
  }
  return (Generic) rexpr_2;
}
#endif

#ifndef DEF_POG_uMEDIATOR_old_uGlueSpecWithPoLst

TYPE_POG_uMEDIATOR_string vdm_POG_uMEDIATOR_old_uGlueSpecWithPoLst() {
  Sequence rexpr_2;
  {
    bool succ_3;
    Generic vdm_POG_uMEDIATOR_ast;
    Record tmpRec_5(vdm_AS_AstCI, length_AS_AstCI);
    tmpRec_5 = Record(vdm_AS_AstCI, length_AS_AstCI);
    Sequence tmpVar_6;
    tmpVar_6 = Sequence().ImpAppend(vdm_SPEC_uAST_GetAst());
    tmpRec_5.SetField(1, tmpVar_6);
    tmpRec_5.SetField(2, Sequence());
    tmpRec_5.SetField(3, Map());
    if (tmpRec_5.Is(vdm_AS_AstCI)) 
      vdm_POG_uMEDIATOR_ast = tmpRec_5.GetField(pos_AS_AstCI_ast);
    else 
      RunTime("Unknown record field selector");
    Generic tmpVal_10;
    bool succ_11 = true;    {
      succ_11 = true;
      if (!vdm_POG_uMEDIATOR_ast.IsSequence()) 
        succ_11 = false;
      if (succ_11) {
        Record selRes_15;
        if (vdm_POG_uMEDIATOR_ast.IsSequence()) {
          Sequence tmpRes_17 = vdm_POG_uMEDIATOR_ast;
          selRes_15 = tmpRes_17[((Int) 1).GetValue()];
        }
        else 
          RunTime("The argument could not be applied");
        bool succ_14 = true;
        {
          succ_14 = true;
          if (selRes_15.IsRecord() && vdm_AS_Definitions == ((Record) selRes_15).GetTag()) {
            Sequence e_l_20;
            for (int i_21 = 1; i_21 <= ((Record) selRes_15).Length(); i_21++) 
              e_l_20.ImpAppend(((Record) selRes_15).GetField(i_21));
            if (succ_14 = 6 == (Int) e_l_20.Length()) {}
          }
          else 
            succ_14 = false;
          if (succ_14) 
            RunTime("Can not evaluate an undefined expression");
        }
        if (!succ_14) {
          Generic vdm_POG_uMEDIATOR_defs;
          Record vdm_POG_uMEDIATOR_nm(vdm_AS_Name, length_AS_Name);
          succ_14 = true;
          if (selRes_15.IsRecord() && vdm_AS_Module == ((Record) selRes_15).GetTag()) {
            Sequence e_l_22;
            for (int i_23 = 1; i_23 <= ((Record) selRes_15).Length(); i_23++) 
              e_l_22.ImpAppend(((Record) selRes_15).GetField(i_23));
            if (succ_14 = 4 == (Int) e_l_22.Length()) {
              vdm_POG_uMEDIATOR_nm = (Generic) e_l_22.Hd();
              vdm_POG_uMEDIATOR_defs = (Generic) e_l_22[3];
            }
          }
          else 
            succ_14 = false;
          if (succ_14) {
            tmpVal_10 = Tuple(2);
            tmpVal_10 = Tuple(tmpVal_10).SetField(1, vdm_PP_uMEDIATOR_trv_uNameName((Generic) vdm_POG_uMEDIATOR_nm));
            Sequence tmpVar_26;
            Record par_27;
            if (vdm_POG_uMEDIATOR_ast.IsSequence()) {
              Sequence tmpRes_29 = vdm_POG_uMEDIATOR_ast;
              par_27 = tmpRes_29[((Int) 1).GetValue()];
            }
            else 
              RunTime("The argument could not be applied");
            tmpVar_26 = vdm_PP_uMEDIATOR_trv_uModule((Generic) par_27);
            tmpVal_10 = Tuple(tmpVal_10).SetField(2, tmpVar_26);
          }
        }
        if (!succ_14) {
          succ_14 = true;
          if (selRes_15.IsRecord() && vdm_AS_ImplModule == ((Record) selRes_15).GetTag()) {
            Sequence e_l_31;
            for (int i_32 = 1; i_32 <= ((Record) selRes_15).Length(); i_32++) 
              e_l_31.ImpAppend(((Record) selRes_15).GetField(i_32));
            if (succ_14 = 4 == (Int) e_l_31.Length()) {}
          }
          else 
            succ_14 = false;
          if (succ_14) 
            RunTime("Can not evaluate an undefined expression");
        }
        if (!succ_14) 
          RunTime("No \'others\' branch in CasesExpr");
      }
    }    if (!succ_11) 
      RunTime("Can not evaluate an undefined expression");
    Generic vdm_POG_uMEDIATOR_mod_uname;
    Generic vdm_POG_uMEDIATOR_pp_umod;
    succ_3 = true;
    if (tmpVal_10.IsTuple()) {
      Sequence e_l_33;
      for (int i_34 = 1; i_34 <= ((Tuple) tmpVal_10).Length(); i_34++) 
        e_l_33.ImpAppend(((Tuple) tmpVal_10).GetField(i_34));
      if (succ_3 = 2 == (Int) e_l_33.Length()) {
        vdm_POG_uMEDIATOR_mod_uname = (Generic) e_l_33.Hd();
        vdm_POG_uMEDIATOR_pp_umod = (Generic) e_l_33[2];
      }
    }
    else 
      succ_3 = false;
    if (!succ_3) 
      RunTime("Pattern match did not succeed in value definition");
    Sequence vdm_POG_uMEDIATOR_pp_upo;
    Sequence par_37;
    {
      Sequence res_l_38;
      Set resBind_s_40;
      Set riseq_44;
      int max_45 = (Int) vdm_POG_uMEDIATOR_polst.Length();
      for (int i_46 = 1; i_46 <= max_45; i_46++) 
        riseq_44.Insert((Int) i_46);
      resBind_s_40 = riseq_44;
      Sequence bind_l_39;
      if ((Int) resBind_s_40.Card() != (Int) 0) 
        bind_l_39 = Sort(resBind_s_40);
      bool succ_41 = true;
      Int vdm_POG_uMEDIATOR_i;
      Generic tmpe_52;
      for (int i_51 = bind_l_39.First(tmpe_52); i_51; i_51 = bind_l_39.Next(tmpe_52)) {
        Int e_42 = tmpe_52;
        vdm_POG_uMEDIATOR_i = e_42;
        if (succ_41) 
          res_l_38.ImpAppend(vdm_POG_uMEDIATOR_pp_uProofObligationAsVdmFunction((Generic) (Record) vdm_POG_uMEDIATOR_polst[vdm_POG_uMEDIATOR_i.GetValue()]));
      }
      par_37 = res_l_38;
    }
    vdm_POG_uMEDIATOR_pp_upo = vdm_POG_uMEDIATOR_List2SeparatorList((Generic) Sequence(";\n\n"), (Generic) par_37);
    Sequence var1_53;
    Sequence var1_54;
    Sequence var1_55;
    Sequence var1_56;
    Sequence var1_57;
    Sequence var1_58;
    Sequence var1_59;
    Sequence var1_60;
    var1_60.ImpConc(Sequence("module ")).ImpConc(vdm_POG_uMEDIATOR_mod_uname);
    var1_59.ImpConc(var1_60).ImpConc(Sequence("\n\n"));
    var1_58.ImpConc(var1_59).ImpConc(Sequence("definitions\n\n"));
    var1_57.ImpConc(var1_58).ImpConc(vdm_POG_uMEDIATOR_pp_umod);
    var1_56.ImpConc(var1_57).ImpConc(Sequence("\n\nfunctions\n\n"));
    var1_55.ImpConc(var1_56).ImpConc(vdm_POG_uMEDIATOR_pp_upo);
    var1_54.ImpConc(var1_55).ImpConc(Sequence("\n\nend "));
    var1_53.ImpConc(var1_54).ImpConc(vdm_POG_uMEDIATOR_mod_uname);
    rexpr_2.ImpConc(var1_53).ImpConc(Sequence("\n"));
  }
  return (Generic) rexpr_2;
}
#endif

#ifndef DEF_POG_uMEDIATOR_setupPOG

void vdm_POG_uMEDIATOR_setupPOG() {
  vdm_POG_uMEDIATOR_polst = Sequence();
  vdm_POG_uMEDIATOR_status = Sequence();
  vdm_POG_uMEDIATOR_typeDefs = vdm_SPEC_uAST_GetTypeDefNames();
  vdm_POG_uMEDIATOR_fnDefs = vdm_SPEC_uAST_GetFnDefNames();
}
#endif

