//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 25-Mar-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _POG_uPAT_h
#define _POG_uPAT_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CHECK.h"
#include "CI.h"
#include "POGTP.h"
#include "POG_uEXPR.h"
#include "REP.h"
#include "POG_uPAT_anonym.h"
enum  {
  vdm_POG_uPAT_POG = TAG_TYPE_POG_uPAT_POG,
  length_POG_uPAT_POG = 3,
  pos_POG_uPAT_POG_po = 1,
  pos_POG_uPAT_POG_fv = 2,
  pos_POG_uPAT_POG_pid = 3
};

class TYPE_POG_uPAT_POG : public Record {
public:

  TYPE_POG_uPAT_POG() : Record(TAG_TYPE_POG_uPAT_POG, 3) {}
  void Init(type_21POGTP_ProofObligationCL p2, type_7AS_NameCS p3, type_7AS_NameCS p4);

  TYPE_POG_uPAT_POG(const Generic &c) : Record(c) {}

  const char * GetTypeName() const { return "TYPE_POG_uPAT_POG"; }
  type_21POGTP_ProofObligationCL get_po() const;
  void set_po(const type_21POGTP_ProofObligationCL &p);
  type_7AS_NameCS get_fv() const;
  void set_fv(const type_7AS_NameCS &p);
  type_7AS_NameCS get_pid() const;
  void set_pid(const type_7AS_NameCS &p);
} ;
void init_POG_uPAT();
TYPE_POG_uPAT_POG vdm_POG_uPAT_pog_uBind(const TYPE_AS_Bind &, const TYPE_POGTP_Context &);
TYPE_POG_uPAT_POG vdm_POG_uPAT_pog_uBindList(const TYPE_AS_BindList &, const TYPE_POGTP_Context &);
TYPE_POG_uPAT_POG vdm_POG_uPAT_pog_uPattern(const TYPE_AS_Pattern &, const TYPE_POGTP_Context &);
TYPE_POG_uPAT_POG vdm_POG_uPAT_pog_uPatternBind(const TYPE_AS_PatternBind &, const TYPE_POGTP_Context &);
TYPE_POG_uPAT_POG vdm_POG_uPAT_pog_uPatternSequence(const type_FL &, const TYPE_POGTP_Context &);
TYPE_POG_uPAT_POG vdm_POG_uPAT_pog_uSetBind(const TYPE_AS_SetBind &, const TYPE_POGTP_Context &);
TYPE_POG_uPAT_POG vdm_POG_uPAT_pog_uTypeBind(const TYPE_AS_TypeBind &, const TYPE_POGTP_Context &);

#endif

