//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Fri 22-Oct-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _POG_uDEF_h
#define _POG_uDEF_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CHECK.h"
#include "CI.h"
#include "GEN_uPO.h"
#include "POGTP.h"
#include "POG_uEXPR.h"
#include "POG_uPAT.h"
#include "REP.h"
#include "POG_uDEF_anonym.h"
;
void init_POG_uDEF();
type_21POGTP_ProofObligationCL vdm_POG_uDEF_pog_uAstCI(const TYPE_AS_AstCI &);
TYPE_POG_uPAT_POG vdm_POG_uDEF_pog_uFnDef(const TYPE_AS_FnDef &, const TYPE_POGTP_Context &);
type_12POG_uPAT_POGC13POGTP_ContextC2P vdm_POG_uDEF_pog_uLocalDefList(const type_FL &, const TYPE_POGTP_Context &);
type_21POGTP_ProofObligationCL vdm_POG_uDEF_pog_uTypeDef(const TYPE_AS_TypeDef &, const TYPE_POGTP_Context &);

#endif

