function drawing = newDrawing

drawing = ...
   struct( ...
     'handle',[], ...
     'label','drawing', ...
     'drawinglist',[], ...
     'type','composition', ...
     'T',eye(4,4), ...
     'color',[], ...
     'line',[], ...
     'vertices',[], ...
     'faces',[] ...
   );