~jojo/toolbox/linux/vppde -j *.rtf
javac -classpath .:/opt/jdk1.1.6v4a/lib/classes.zip:/home/jojo/toolbox/spec/test/metaivHenrik/dk/ifad/toolbox/VDM/VDM.jar *.java
java GraphicsTest


test options
~jojo/toolbox/linux/vppde -j -s *.rtf
