# Denotational Semantics of the programming language
#           NewSpeak. (Paul Mukherjee)

TARGETS = newspeak.avdm.tar.gz newspeak.ps.gz

BASEFILE = newspeak

newspeak.avdm.tar.gz: newspeak.avdm

newspeak.ps.gz: newspeak.ps

newspeak.ps: newspeak.avdm.tex 

include ../Make.rules
