//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Fri 10-Jan-97 by the VDM-SLtoC++ Code Generator
// (vdmde - v3.0l - Fri 10-Jan-97)
//
// Supported compiler: g++ version 2.7.2
//

#ifndef _OLD_h
#define _OLD_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "REP.h"

void init_OLD();
Record vdm_OLD_OldNameInExpr(Record);

#endif

