//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Fri 10-Jan-97 by the VDM-SLtoC++ Code Generator
// (vdmde - v3.0l - Fri 10-Jan-97)
//
// Supported compiler: g++ version 2.7.2
//

#ifndef _SETTINGS_h
#define _SETTINGS_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"

enum  {
  vdm_SETTINGS_Settings = 186,
  length_SETTINGS_Settings = 4,
  pos_SETTINGS_Settings_dtc = 1,
  pos_SETTINGS_Settings_precheck = 2,
  pos_SETTINGS_Settings_postcheck = 3,
  pos_SETTINGS_Settings_invar = 4
};
void init_SETTINGS();
Bool vdm_SETTINGS_DTC();
void vdm_SETTINGS_DtcOff();
void vdm_SETTINGS_DtcOn();
Bool vdm_SETTINGS_INV();
void vdm_SETTINGS_InvOff();
void vdm_SETTINGS_InvOn();
Bool vdm_SETTINGS_PostCheck();
void vdm_SETTINGS_PostOff();
void vdm_SETTINGS_PostOn();
Bool vdm_SETTINGS_PreCheck();
void vdm_SETTINGS_PreOff();
void vdm_SETTINGS_PreOn();

#endif

