//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Fri 10-Jan-97 by the VDM-SLtoC++ Code Generator
// (vdmde - v3.0l - Fri 10-Jan-97)
//
// Supported compiler: g++ version 2.7.2
//



#include "SETTINGS.h"

static Bool vdm_SETTINGS_dtc;
static Bool vdm_SETTINGS_precheck;
static Bool vdm_SETTINGS_postcheck;
static Bool vdm_SETTINGS_invar;

void init_SETTINGS() {
  vdm_SETTINGS_dtc = (Bool) false;
  vdm_SETTINGS_precheck = (Bool) false;
  vdm_SETTINGS_postcheck = (Bool) false;
  vdm_SETTINGS_invar = (Bool) false;
}

Bool vdm_SETTINGS_DTC() {
  Bool rexpr_2;
  rexpr_2 = vdm_SETTINGS_dtc;
  return rexpr_2;
}

void vdm_SETTINGS_DtcOff() {
  Bool rhs_2;
  rhs_2 = (Bool) false;
  vdm_SETTINGS_dtc = rhs_2;
}

void vdm_SETTINGS_DtcOn() {
  Bool rhs_2;
  rhs_2 = (Bool) true;
  vdm_SETTINGS_dtc = rhs_2;
}

Bool vdm_SETTINGS_INV() {
  Bool rexpr_2;
  rexpr_2 = vdm_SETTINGS_invar;
  return rexpr_2;
}

void vdm_SETTINGS_InvOff() {
  Bool rhs_2;
  rhs_2 = (Bool) false;
  vdm_SETTINGS_invar = rhs_2;
}

void vdm_SETTINGS_InvOn() {
  Bool rhs_2;
  rhs_2 = (Bool) true;
  vdm_SETTINGS_invar = rhs_2;
}

Bool vdm_SETTINGS_PostCheck() {
  Bool rexpr_2;
  rexpr_2 = vdm_SETTINGS_postcheck;
  return rexpr_2;
}

void vdm_SETTINGS_PostOff() {
  Bool rhs_2;
  rhs_2 = (Bool) false;
  vdm_SETTINGS_postcheck = rhs_2;
}

void vdm_SETTINGS_PostOn() {
  Bool rhs_2;
  rhs_2 = (Bool) true;
  vdm_SETTINGS_postcheck = rhs_2;
}

Bool vdm_SETTINGS_PreCheck() {
  Bool rexpr_2;
  rexpr_2 = vdm_SETTINGS_precheck;
  return rexpr_2;
}

void vdm_SETTINGS_PreOff() {
  Bool rhs_2;
  rhs_2 = (Bool) false;
  vdm_SETTINGS_precheck = rhs_2;
}

void vdm_SETTINGS_PreOn() {
  Bool rhs_2;
  rhs_2 = (Bool) true;
  vdm_SETTINGS_precheck = rhs_2;
}
