
TARGETS = acs.avdm.tar.gz acs.ps.gz

BASEFILE = acs

# Specification of an ammunition control system.
acs.avdm.tar.gz: acs.avdm acs.tex

acs.ps.gz: acs.ps

acs.dvi: acs.tex acs.avdm.tex

include ../Make.rules


