//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Mon 11-Oct-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _PP_uTAR_uDEF_h
#define _PP_uTAR_uDEF_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CI.h"
#include "PP_uTAR_uEXPR.h"
#include "PP_uTAR_uPAT.h"
#include "PP_uTAR_uTYPE.h"
#include "REP.h"
#include "PP_uTAR_uDEF_anonym.h"
;
void init_PP_uTAR_uDEF();
TYPE_PP_uTAR_uDEF_string vdm_PP_uTAR_uDEF_List2CommaList(const type_cLL &);
TYPE_PP_uTAR_uDEF_string vdm_PP_uTAR_uDEF_List2SeparatorList(const TYPE_PP_uTAR_uDEF_string &, const type_cLL &);
TYPE_PP_uTAR_uDEF_string vdm_PP_uTAR_uDEF_Map2String(const type_7AS_NameCcLM &);
type_typevariableL vdm_PP_uTAR_uDEF_SetToSeq(const type_typevariableS &);
TYPE_PP_uTAR_uDEF_AstCI vdm_PP_uTAR_uDEF_tar_uAstCI(const type_cL &, const type_19CI_TokenContextInfoCL &, const TYPE_CI_FileIdMap &);
TYPE_PP_uTAR_uDEF_Definitions vdm_PP_uTAR_uDEF_tar_uDefinitions(const type_7AS_NameCcLM &, const type_cLL &, const type_7AS_NameCcLM &, const type_7AS_NameCFM &, const Generic &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_Document vdm_PP_uTAR_uDEF_tar_uDocument(const type_UL &);
Bool vdm_PP_uTAR_uDEF_pre_tar_uDocument(const type_UL &);
TYPE_PP_uTAR_uDEF_ExplFnDef vdm_PP_uTAR_uDEF_tar_uExplFunction(const TYPE_PP_uTAR_uEXPR_NameName &, const TYPE_PP_uTAR_uDEF_TypeVarList &, const TYPE_PP_uTAR_uTYPE_FnType &, const TYPE_PP_uTAR_uDEF_ParametersList &, const TYPE_PP_uTAR_uDEF_FnBody &, const Generic &, const Generic &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_ExtExplFnDef vdm_PP_uTAR_uDEF_tar_uExtExplFunction(const TYPE_PP_uTAR_uEXPR_NameName &, const TYPE_PP_uTAR_uDEF_TypeVarList &, const TYPE_PP_uTAR_uDEF_ParameterTypes &, const type_cLL &, const TYPE_PP_uTAR_uDEF_FnBody &, const Generic &, const Generic &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_FnBody vdm_PP_uTAR_uDEF_tar_uFnBody(const Generic &, const TYPE_CI_ContextId &);
type_cLL vdm_PP_uTAR_uDEF_tar_uGlobalValueDef(const type_cLL &);
TYPE_PP_uTAR_uDEF_ImplFnDef vdm_PP_uTAR_uDEF_tar_uImplFunction(const TYPE_PP_uTAR_uEXPR_NameName &, const TYPE_PP_uTAR_uDEF_TypeVarList &, const TYPE_PP_uTAR_uDEF_ParameterTypes &, const type_cLL &, const Generic &, const TYPE_PP_uTAR_uEXPR_Expr &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_Invariant vdm_PP_uTAR_uDEF_tar_uInvariant(const TYPE_PP_uTAR_uPAT_Pattern &, const TYPE_PP_uTAR_uEXPR_Expr &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_Module vdm_PP_uTAR_uDEF_tar_uModule(const TYPE_PP_uTAR_uEXPR_NameName &, const TYPE_PP_uTAR_uDEF_Interface &, const TYPE_PP_uTAR_uDEF_Definitions &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_NameType vdm_PP_uTAR_uDEF_tar_uNameType(const TYPE_PP_uTAR_uEXPR_NameName &, const TYPE_PP_uTAR_uTYPE_Type &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_string vdm_PP_uTAR_uDEF_tar_uParametersList(const TYPE_PP_uTAR_uDEF_ParametersList &);
TYPE_PP_uTAR_uDEF_PatTypePair vdm_PP_uTAR_uDEF_tar_uPatTypePair(const type_cLL &, const TYPE_PP_uTAR_uTYPE_Type &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_TypeDef vdm_PP_uTAR_uDEF_tar_uTypeDef(const TYPE_PP_uTAR_uEXPR_NameType &, const TYPE_AS_Type &, const TYPE_PP_uTAR_uTYPE_Type &, const Generic &, const TYPE_CI_ContextId &);
TYPE_PP_uTAR_uDEF_ValueDef vdm_PP_uTAR_uDEF_tar_uValueDef(const TYPE_PP_uTAR_uPAT_Pattern &, const Generic &, const TYPE_PP_uTAR_uEXPR_Expr &, const TYPE_CI_ContextId &);

#endif

