#!/bin/bash

if [[ -z "${PYTHON}" ]]; then
  PYTHON=/usr/bin/python
fi
if [[ -z "${OMNIORBDIR}" ]]; then
  OMNIORBDIR=/usr/local/omniORB
fi
PYVERSION=$(${PYTHON} -V 2>&1 | awk -F ' ' '{print $2}' | awk -F '.' '{print $1 "." $2}')
SITEPACKAGES=${OMNIORBDIR}/lib/python${PYVERSION}/site-packages
SITEPACKAGES64=${OMNIORBDIR}/lib64/python${PYVERSION}/site-packages
PYTHONPATH=${SITEPACKAGES}/omniORB:${SITEPACKAGES}
if [ -d "${SITEPACKAGES64}" ]; then
  PYTHONPATH=${PYTHONPATH}:${SITEPACKAGES64}/omniORB:${SITEPACKAGES64}
fi
export PYTHONPATH
OSTYPE=$(uname)
if [ "Darwin" = ${OSTYPE} ]; then
  export DYLD_LIBRARY_PATH=$OMNIORBDIR/lib:$DYLD_LIBRARY_PATH
else
  export LD_LIBRARY_PATH=$OMNIORBDIR/lib:$LD_LIBRARY_PATH
fi
IFS_BACKUP=${IFS}
IFS=$'\n'
DIR=`dirname $0`
IFS=${IFS_BACKUP}
"${DIR}/powertest.script" "$@"
