# A crosswords assistant.

TARGETS = crossword.vdm.gz crossword.ps.gz 

EXTRACLEAN = crossword.vdm.ps 

BASEFILE = crossword

crossword.vdm.gz : crossword.vdm

crossword.ps.gz : crossword.vdm.ps

include ../Make.rules
