//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 12-Oct-2000 by the VDM++ JAVA Code Generator
//
// Supported compilers:
// jdk1.2
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO

// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package


// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.vdmtools.VDM.*;
import java.util.*;
// ***** VDMTOOLS END Name=imports



public class B3 implements EvaluatePP {


// ***** VDMTOOLS START Name=T KEEP=YES
  public static class T implements Record {

    public Integer i;

    public String j;


    public T () {}


    public T (Integer p1, String p2) {
      i = p1;
      j = p2;
      System.out.println(p2);
    }


    public T (Long p1, String p2) {
      i = new Integer(p1.intValue());
      j = p2;
      System.out.println(p2);
    }


    public Object clone () {
      return new T(i,j);
    }


    public String toString () {
      return "mk_B3`T(" + UTIL.toString(i) + "," + UTIL.toString(j) + ")";
    }


    public boolean equals (Object obj) {
      if (!(obj instanceof T)) 
        return false;
      else {        
        T temp = (T) obj;

        return UTIL.equals(i, temp.i) && UTIL.equals(j, temp.j);
      }
    }


    public int hashCode () {
      return (i == null ? 0 : i.hashCode()) + (j == null ? 0 : j.hashCode());
    }

  }
// ***** VDMTOOLS END Name=T
 ;

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=sentinel KEEP=NO
  volatile Sentinel sentinel;
// ***** VDMTOOLS END Name=sentinel


// ***** VDMTOOLS START Name=B3Sentinel KEEP=NO
  class B3Sentinel extends Sentinel {

    public final int nr_functions = 0;


    public B3Sentinel () throws CGException{}


    public B3Sentinel (EvaluatePP instance) throws CGException{
      init(nr_functions, instance);
    }

  }
// ***** VDMTOOLS END Name=B3Sentinel
;

// ***** VDMTOOLS START Name=evaluatePP KEEP=NO
  public Boolean evaluatePP (int fnr) throws CGException{
    return new Boolean(true);
  }
// ***** VDMTOOLS END Name=evaluatePP


// ***** VDMTOOLS START Name=setSentinel KEEP=NO
  public void setSentinel () {
    try{
      sentinel = new B3Sentinel(this);
    }
    catch (CGException e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=setSentinel


// ***** VDMTOOLS START Name=B3 KEEP=NO
  public B3 () {
    try{
      setSentinel();
    }
    catch (Throwable e) {
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=B3

}
;
