
TARGETS = realm.vdm.tar.gz realm.ps.gz

BASEFILE = realm

# Specification of the REALM datatype
realm.vdm.tar.gz: realm.vdm realm.sh test.vdm realm.bib

realm.ps.gz: realm.ps

realm.ps: realm.vdm.tex test.vdm.tex 

include ../Make.rules


