//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//



#include "BulletinMeteo.h"

vdm_BulletinMeteo::vdm_BulletinMeteo() { RegisterAsDerived(vdm_GetId()); }

void vdm_BulletinMeteo::vdm_SetQNH(const Record &vdm_station, const Real &vdm_qnh) {
  Map rhs_1;
  Map modmap_2;
  Map res_m_5;
  NotSupported("The construct is not supported: type bind");
  modmap_2 = res_m_5;
  rhs_1 = vdm_qnh_ulocale;  rhs_1.ImpOverride(modmap_2);
  vdm_qnh_ulocale = rhs_1;
}

void vdm_BulletinMeteo::vdm_SetPosition(const Record &vdm_station, const Tuple &vdm_position) { vdm_position_ude_ustation.ImpModify(vdm_station, vdm_position); }

Real vdm_BulletinMeteo::vdm_GetQNH(const Tuple &vdm_position) { return (Real) 1013.25; }
