//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//

#ifndef _MSAWTypes_h
#define _MSAWTypes_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"



class vdm_MSAWTypes : public virtual CGBase {
protected:
  Int vdm_BalayageRadar;
  Int vdm_NMperCoordonnee;
  Int vdm_Secondes;
  enum  {
    vdm_ModeA = 1,
    length_ModeA = 1,
    pos_ModeA_id = 1,
    vdm_StationMeteo = 2,
    length_StationMeteo = 1,
    pos_StationMeteo_id = 1
  } ;
  Bool vdm_inv_Coordonnee(const Int &);
  Bool vdm_inv_Degrees(const Real &);
  virtual Bool vdm_PlusTard(const Int &, const Int &);
  virtual Int vdm_LaPlusRecente(const Set &);
  virtual Bool vdm_pre_LaPlusRecente(const Set &);
  virtual Real vdm_Distance(const Tuple &, const Record &);
public:

  virtual vdm_MSAWTypes * Get_vdm_MSAWTypes() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_MSAWTypes()); }

  int vdm_GetId() { return VDM_MSAWTypes; }
   vdm_MSAWTypes();

  virtual ~vdm_MSAWTypes() {}
};

#endif

