//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//

#ifndef _Parametres_h
#define _Parametres_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"
#include "MSAWTypes.h"



class vdm_Parametres : public virtual vdm_MSAWTypes {
protected:
  Int vdm_DureeExtrapolation;
  Tuple vdm_VitesseMaximale;
public:

  virtual vdm_Parametres * Get_vdm_Parametres() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_Parametres()); }

  int vdm_GetId() { return VDM_Parametres; }
   vdm_Parametres();

  virtual ~vdm_Parametres() {}
};

#endif

