//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//



#include "Parametres.h"

vdm_Parametres::vdm_Parametres() {
  RegisterAsDerived(vdm_GetId());
  {
    Tuple tmpVal_1(3);
    tmpVal_1 = Tuple(3);
    tmpVal_1.SetField(1, (Int) 100);
    tmpVal_1.SetField(2, (Int) 100);
    tmpVal_1.SetField(3, (Int) 100);
    vdm_VitesseMaximale = tmpVal_1;
  }
  {
    Int tmpVal_1;
    tmpVal_1 = (Int) 20;
    vdm_DureeExtrapolation = tmpVal_1;
  }
}
