//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//

#ifndef _Polygone_h
#define _Polygone_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"
#include "MSAWTypes.h"



class vdm_Polygone : public virtual vdm_MSAWTypes {
protected:
  Set vdm_sommets;
  virtual Bool vdm_DansPolygone(const Tuple &, const Set &);
public:

  virtual vdm_Polygone * Get_vdm_Polygone() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_Polygone()); }

  int vdm_GetId() { return VDM_Polygone; }
   vdm_Polygone();

  virtual ~vdm_Polygone() {}
};

#endif

