//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//

#ifndef _TclTkView_h
#define _TclTkView_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"
#include "View.h"



class vdm_TclTkView : public virtual vdm_View {
public:

  virtual vdm_TclTkView * Get_vdm_TclTkView() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_TclTkView()); }

  int vdm_GetId() { return VDM_TclTkView; }
  virtual void vdm_ShowAlarm(const Record &, const ObjectRef &);
  virtual void vdm_ShowObstacleArtificiel(const Tuple &, const Real &, const Int &);
  virtual void vdm_ShowZoneAeroport(const Tuple &, const Real &, const Int &, const Real &);
  virtual void vdm_ShowRadarData(const Record &, const Tuple &, const Int &);
  virtual void vdm_ShowSegmentDePrediction(const Tuple &, const Tuple &);
  virtual void vdm_ShowTime(const Int &);
   vdm_TclTkView();

  virtual ~vdm_TclTkView() {}
};

#endif

