//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//



#include "Terrain.h"
#include "SegmentDePrediction.h"

vdm_Terrain::vdm_Terrain() {
  RegisterAsDerived(vdm_GetId());
  vdm_mosaique = Map();
}

void vdm_Terrain::vdm_SetAltitude(const Tuple &vdm_coordonnees, const Int &vdm_altitude) { vdm_mosaique.ImpModify(vdm_coordonnees, vdm_altitude); }

Bool vdm_Terrain::vdm_Intersection(const ObjectRef &vdm_segment_ude_uprediction) {
  Set tmpVal_2 = ObjGet_vdm_SegmentDePrediction(vdm_segment_ude_uprediction)->vdm_GetPoints();
  Set vdm_points_ude_uvecteur;
  vdm_points_ude_uvecteur = tmpVal_2;
  if (((Bool) (vdm_points_ude_uvecteur == Set())).GetValue()) 
    return (Bool) false;
  else {
    Bool rexpr_7;
    bool tmpQuant_8 = false;
    {
      bool succ_12 = true;

      Tuple vdm_xy(2);      Int vdm_z;
      {
        Generic tmpe_18;
        for (int bb_17 = vdm_points_ude_uvecteur.First(tmpe_18); bb_17 && !tmpQuant_8; bb_17 = vdm_points_ude_uvecteur.Next(tmpe_18)) {
          Tuple elem_14 = tmpe_18;
          succ_12 = true;          if (elem_14.IsTuple()) {
            Sequence e_l_15;
            for (int i_16 = 1; i_16 <= ((Tuple) elem_14).Length(); i_16++) 
              e_l_15.ImpAppend(((Tuple) elem_14).GetField(i_16));
            if (succ_12 = 2 == (Int) e_l_15.Length()) {
              succ_12 = true;
              if (((Bool) ((Generic) e_l_15.Hd()).IsTuple()).GetValue()) 
                vdm_xy = (Generic) e_l_15.Hd();
              else 
                succ_12 = false;
              if (succ_12) { if (((Bool) (IsInteger((Generic) e_l_15[2]) && ((Int) (Generic) e_l_15[2]).GetValue() >= 0)).GetValue()) 
   vdm_z = (Generic) e_l_15[2];
 else 
   succ_12 = false; }
            }
          }
          else 
            succ_12 = false;          if (succ_12) { if (((Bool) ((vdm_z.GetValue()) <= (((Int) 1).GetValue()))).GetValue()) 
   tmpQuant_8 = true; }
        }
      }
    }
    rexpr_7 = (Bool) tmpQuant_8;
    return rexpr_7;
  }
}
