//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//

#ifndef _Vecteur3D_h
#define _Vecteur3D_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"
#include "MSAWTypes.h"



class vdm_Vecteur3D : public virtual vdm_MSAWTypes {
protected:
  Tuple vdm_xy_uqueue;
  Int vdm_z_uqueue;
  Tuple vdm_xy_utete;
  Int vdm_z_utete;
  virtual Real vdm_Rico(const Real &, const Real &, const Real &, const Real &);
  virtual Real vdm_Ricoz(const Real &, const Real &, const Real &, const Real &, const Real &, const Real &);
  virtual Bool vdm_OuterTest(const Real &, const Real &, const Real &);
  virtual Bool vdm_InnerTest(const Real &, const Real &, const Real &);
public:

  virtual vdm_Vecteur3D * Get_vdm_Vecteur3D() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_Vecteur3D()); }

  int vdm_GetId() { return VDM_Vecteur3D; }
  virtual Set vdm_GetPoints();
   vdm_Vecteur3D();

  virtual ~vdm_Vecteur3D() {}
};

#endif

