//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//

#ifndef _VisualObstacleArtificiel_h
#define _VisualObstacleArtificiel_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"
#include "ObstacleArtificiel.h"



class vdm_VisualObstacleArtificiel : public virtual vdm_ObstacleArtificiel {
protected:
  ObjectRef vdm_view;
public:

  virtual vdm_VisualObstacleArtificiel * Get_vdm_VisualObstacleArtificiel() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_VisualObstacleArtificiel()); }

  int vdm_GetId() { return VDM_VisualObstacleArtificiel; }
  virtual void vdm_Set(const Tuple &, const Real &, const Int &, const ObjectRef &);
   vdm_VisualObstacleArtificiel();

  virtual ~vdm_VisualObstacleArtificiel() {}
};

#endif

