//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//

#ifndef _WorkSpace_h
#define _WorkSpace_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"
#include "MSAWTypes.h"



class vdm_WorkSpace : public virtual vdm_MSAWTypes {
protected:
  ObjectRef vdm_pistes_uradar;
  ObjectRef vdm_bulletin_umeteo;
  ObjectRef vdm_terrain;
  Set vdm_obstacles;
  ObjectRef vdm_detecteur;
  virtual Sequence vdm_OrdreDeTraitement(const Set &);
public:

  virtual vdm_WorkSpace * Get_vdm_WorkSpace() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_WorkSpace()); }

  int vdm_GetId() { return VDM_WorkSpace; }
  virtual void vdm_SetObstacle(const ObjectRef &);
  virtual void vdm_TraiterPistesRadar();
   vdm_WorkSpace();

  virtual ~vdm_WorkSpace() {}
};

#endif

