//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Wed 05-Nov-97 by the VDM++toC++ Code Generator
// (v6.0e - Tue 04-Nov-97)
//
// Supported compilers:
// 	g++ version 2.7.2 on SunOS4, SunOS5, Linux, HP-UX10
// 	Dec cxx version 5.5 on Alpha OSF1
// 	VC++ version 5.0 on Windows95, Windows NT
//

#ifndef _ZoneMilitaire_h
#define _ZoneMilitaire_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"
#include "Obstacle.h"
#include "Polygone.h"



class vdm_ZoneMilitaire : 
  public virtual vdm_Obstacle, 
  public virtual vdm_Polygone {
protected:
  Int vdm_niveau_uminimal;
  Int vdm_niveau_umaximal;
  Generic vdm_statut;
public:

  virtual vdm_ZoneMilitaire * Get_vdm_ZoneMilitaire() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_ZoneMilitaire()); }

  int vdm_GetId() { return VDM_ZoneMilitaire; }
  virtual void vdm_SetStatut(const Generic &);
  virtual Bool vdm_Intersection(const ObjectRef &);
   vdm_ZoneMilitaire();

  virtual ~vdm_ZoneMilitaire() {}
};

#endif

