//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Mon 11-Oct-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _TRF_uTRA_uPAT_h
#define _TRF_uTRA_uPAT_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CI.h"
#include "REP.h"
#include "TRF_uTAR_uDEF.h"
#include "TRF_uTAR_uEXPR.h"
#include "TRF_uTAR_uPAT.h"
#include "TRF_uTAR_uTYPE.h"
#include "TRF_uTRA_uEXPR.h"
#include "TRF_uTRA_uTYPE.h"
#include "TRF_uTRA_uPAT_anonym.h"
;
void init_TRF_uTRA_uPAT();
TYPE_TRF_uTAR_uPAT_Bind vdm_TRF_uTRA_uPAT_trv_uBind(const TYPE_AS_Bind &);
TYPE_TRF_uTAR_uPAT_BindList vdm_TRF_uTRA_uPAT_trv_uBindList(const TYPE_AS_BindList &);
TYPE_TRF_uTAR_uPAT_Pattern vdm_TRF_uTRA_uPAT_trv_uPattern(const TYPE_AS_Pattern &);
TYPE_TRF_uTAR_uPAT_PatternBind vdm_TRF_uTRA_uPAT_trv_uPatternBind(const TYPE_AS_PatternBind &);
TYPE_TRF_uTAR_uPAT_SetBind vdm_TRF_uTRA_uPAT_trv_uSetBind(const TYPE_AS_SetBind &);
TYPE_TRF_uTAR_uPAT_TypeBind vdm_TRF_uTRA_uPAT_trv_uTypeBind(const TYPE_AS_TypeBind &);

#endif

