//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 23-Mar-2000 by the VDM-SL to C++ Code Generator
// (v3.4o - Mon 20-Mar-00)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//



#include "TRANS.h"


void init_TRANS_VDMLib () {  VDMGetDefaultRecInfoMap().NewTag(TOKEN, 1);
  VDMGetDefaultRecInfoMap().SetSymTag(TOKEN, "token");

}
#ifdef DEF_TRANS_USERIMPL

#include "TRANS_userimpl.cc"

#endif


void init_TRANS () { init_TRANS_VDMLib();
}
#ifndef DEF_TRANS_BinaryOpTable

TYPE_HOL_term vdm_TRANS_BinaryOpTable (const TYPE_AS_BinaryOp &vdm_TRANS_op, const TYPE_HOL_term_utype &vdm_TRANS_tp1, const TYPE_HOL_term_utype &vdm_TRANS_tp2, const TYPE_HOL_term_utype &vdm_TRANS_res_utp) {  Generic varRes_6;
  {    Record vdm_TRANS_tp(vdm_HOL_vartype, length_HOL_vartype);
    vdm_TRANS_tp = Record(vdm_HOL_vartype, length_HOL_vartype);
    vdm_TRANS_tp.SetField(1, Sequence("\'a"));
    bool succ_10 = true;
    {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMPLUS") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$+"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMMINUS") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$-"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMMULT") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$*"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMDIV") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$DIV"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMREM") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$REM"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMMOD") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$MOD"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "INTDIV") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$INTDIV"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMEXP") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$EXP"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMLT") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$<"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMLE") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$<="));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMGT") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$>"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NUMGE") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$>="));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NE") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$<>"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "SETUNION") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$UNION"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "SETINTERSECT") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$INTER"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "SETMINUS") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$DIFF"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "SUBSET") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$SUBSET"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "PROPERSUBSET") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$PSUBSET"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "INSET") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$IN"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "NOTINSET") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$NOTIN"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "SEQCONC") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$%%"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "MAPMERGE") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$MUNION"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "MAPDOMRESTTO") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$<:"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "MAPDOMRESTBY") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$<-:"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "MAPRNGRESTTO") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$:>"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "MAPRNGRESTBY") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$:->"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) {      succ_10 = true;

      if (vdm_TRANS_op != (Quote) "COMPOSE") 
        succ_10 = false;

      if (succ_10) {        varRes_6 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_6 = Record(varRes_6).SetField(1, Sequence("$o"));
        varRes_6 = Record(varRes_6).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_10) 
      RunTime("Can not evaluate an undefined expression");

  }
  return (Generic) varRes_6;

}
#endif

#ifndef DEF_TRANS_BinaryRelTable

TYPE_HOL_term vdm_TRANS_BinaryRelTable (const TYPE_AS_BinaryOp &vdm_TRANS_op, const TYPE_HOL_term_utype &vdm_TRANS_tp1, const TYPE_HOL_term_utype &vdm_TRANS_tp2) {
 return (Generic) vdm_TRANS_BinaryOpTable((Generic) vdm_TRANS_op, (Generic) vdm_TRANS_tp1, (Generic) vdm_TRANS_tp2, (Generic) Record(vdm_HOL_Bool_utype, length_HOL_Bool_utype));
}
#endif

#ifndef DEF_TRANS_UnaryOpTable

TYPE_HOL_term vdm_TRANS_UnaryOpTable (const TYPE_AS_UnaryOp &vdm_TRANS_op, const TYPE_HOL_term_utype &vdm_TRANS_opd_utp, const TYPE_HOL_term_utype &vdm_TRANS_res_utp) {  Generic varRes_5;
  {    Record vdm_TRANS_tp(vdm_HOL_vartype, length_HOL_vartype);
    vdm_TRANS_tp = Record(vdm_HOL_vartype, length_HOL_vartype);
    vdm_TRANS_tp.SetField(1, Sequence("\'a"));
    bool succ_9 = true;
    {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "NUMPLUS") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("PLUSSIGN"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "NUMMINUS") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("MINUSSIGN"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "NUMABS") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("ABS"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "FLOOR") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("FLOOR"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "NOT") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("~"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SETCARD") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("CARD"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SETDISTRUNION") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("DUNION"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SETDISTRINTERSECT") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("DINTER"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SETPOWER") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("POWER"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SEQLEN") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("LENGTH"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SEQDISTRCONC") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("FLAT"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SEQELEMS") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("ELEMS"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SEQINDICES") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("INDS"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SEQTAIL") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("TL"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "SEQHEAD") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("HD"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "MAPDOM") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("FDOM"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "MAPRNG") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("FRANGE"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_op != (Quote) "MAPDISTRMERGE") 
        succ_9 = false;

      if (succ_9) {        varRes_5 = Record(vdm_HOL_Const, length_HOL_Const);
        varRes_5 = Record(varRes_5).SetField(1, Sequence("DMERGE"));
        varRes_5 = Record(varRes_5).SetField(2, vdm_TRANS_tp);

      }

    }

    if (!succ_9) 
      RunTime("Can not evaluate an undefined expression");

  }
  return (Generic) varRes_5;

}
#endif

#ifndef DEF_TRANS_VdmToHolTable

TYPE_HOL_term vdm_TRANS_VdmToHolTable (const TYPE_TRANS_VdmToHol &vdm_TRANS_cons, const type_FL &vdm_TRANS_stp) {  Record varRes_4(vdm_HOL_Const, length_HOL_Const);
  {    Record vdm_TRANS_tp(vdm_HOL_vartype, length_HOL_vartype);
    vdm_TRANS_tp = Record(vdm_HOL_vartype, length_HOL_vartype);
    vdm_TRANS_tp.SetField(1, Sequence("\'a"));
    Generic vdm_TRANS_op;
    bool succ_9 = true;
    {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "ARBITRARY") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("ARBITRARY");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "CASES") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("CASES");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "LET_BE_ST") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("LET_BE_ST");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SETENUM") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("SETENUM");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SETCOMP") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("SETCOMP");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SETRANGE") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("SETRANGE");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SEQENUM") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("SEQENUM");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SEQCOMP") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("SEQCOMP");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SUBSEQ") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("SUBSEQ");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SEQMODIF") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("$SEQMODIF");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SEQAPPLY") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("$SEQAPPLY");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "MAPENUM") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("MAPENUM");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "MAPCOMP") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("MAPCOMP");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "MOVERRIDE") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("$MOVERRIDE");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "NONE") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("NONE");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "SOME") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("SOME");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "PROJ") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("PROJ");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "RECORDCONS") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("RECORDCONS");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "RECORDMODIF") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("RECORDMODIF");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "FAPPLY") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("FAPPLY");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "TOKENCONS") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("TOKENCONS");

    }

    if (!succ_9) {      succ_9 = true;

      if (vdm_TRANS_cons != (Quote) "FINITE") 
        succ_9 = false;

      if (succ_9) 
        vdm_TRANS_op = Sequence("FINITE");

    }

    if (!succ_9) 
      RunTime("Can not evaluate an undefined expression");
    varRes_4 = Record(vdm_HOL_Const, length_HOL_Const);
    varRes_4.SetField(1, vdm_TRANS_op);
    varRes_4.SetField(2, vdm_TRANS_tp);

  }
  return (Generic) varRes_4;

}
#endif

