//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Fri 29-Oct-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//



#include "TRL_uTAR_uTYPE_userdef.h"
#include "metaiv.h"
#include "TRL_uTAR_uTYPE.h"
#include "AS.h"
#include "CI.h"
#include "HOL.h"
#include "REP.h"
