//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2013-02-19 by the VDM++ to JAVA Code Generator
// (v9.0.2 - Mon 18-Feb-2013 16:54:39 +0900)
//
// Supported compilers: jdk 1.4/1.5/1.6
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import java.util.List;
import java.util.ArrayList;
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Sentinel;
import jp.vdmtools.VDM.EvaluatePP;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class external_Example {

// ***** VDMTOOLS START Name=parent KEEP=NO
  Example parent = null;
// ***** VDMTOOLS END Name=parent


// ***** VDMTOOLS START Name=external_Example#1|Example KEEP=NO
  public external_Example (Example parentExample) {
    parent = parentExample;
  }
// ***** VDMTOOLS END Name=external_Example#1|Example


// ***** VDMTOOLS START Name=external_Example KEEP=NO
  public external_Example () { }
// ***** VDMTOOLS END Name=external_Example


// ***** VDMTOOLS START Name=impl_f#1|Number KEEP=YES
  public List impl_f (final Number n) throws CGException {
    List childResult_2 = new ArrayList();
    for (int i = 0; i < 10; i++)
      childResult_2.add(new Integer(i));
    return childResult_2;
  }
// ***** VDMTOOLS END Name=impl_f#1|Number


// ***** VDMTOOLS START Name=impl_extop#1|Number KEEP=YES
  public List impl_extop (final Number n) throws CGException {
    List childResult_2 = new ArrayList();
    for (int i = 0; i < 5; i++)
      childResult_2.add(new Integer(i));
    return childResult_2;
  }
// ***** VDMTOOLS END Name=impl_extop#1|Number


// ***** VDMTOOLS START Name=impl_ReturnList#1|List KEEP=YES
  public List impl_ReturnList (final List s) throws CGException {
      List res = new ArrayList(s);
      res.add(new Example());
      return res;
  }
// ***** VDMTOOLS END Name=impl_ReturnList#1|List

}
;
