//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Tue 30-Oct-2001 by the VDM++ JAVA Code Generator
// (v6.7.19 - Mon 29-Oct-2001)
//
// Supported compilers:
// jdk1.3
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO

// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package jp.vdmtools.VDM.jdk;

// ***** VDMTOOLS END Name=package


// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.vdmtools.VDM.CGException;
import jp.vdmtools.VDM.UTIL;

// ***** VDMTOOLS END Name=imports


public class JavaTextParseException extends JavaLangException {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
    static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp

// ***** VDMTOOLS START Name=errorOffset KEEP=NO
    private Integer errorOffset = null;
// ***** VDMTOOLS END Name=errorOffset

// ***** VDMTOOLS START Name=CLASS KEEP=NO
    private static final JavaLangClass CLASS = (JavaLangClass) new JavaLangClass(new String("JavaTextParseException"), new quotes.CLASS(), Boolean.FALSE);
// ***** VDMTOOLS END Name=CLASS


// ***** VDMTOOLS START Name=JavaTextParseException KEEP=NO
    public JavaTextParseException() throws CGException {
    }
// ***** VDMTOOLS END Name=JavaTextParseException


// ***** VDMTOOLS START Name=getClass KEEP=NO
    public JavaLangClass getJClass() throws CGException {
        return (JavaLangClass) CLASS;
    }
// ***** VDMTOOLS END Name=getClass


// ***** VDMTOOLS START Name=getErrorOffset KEEP=NO
    public Integer getErrorOffset() throws CGException {
        return errorOffset;
    }
// ***** VDMTOOLS END Name=getErrorOffset


// ***** VDMTOOLS START Name=JavaTextParseException KEEP=NO
    public JavaTextParseException(final quotes.NIL var_1_1) throws CGException {
        this();
        isNil = Boolean.TRUE;
    }
// ***** VDMTOOLS END Name=JavaTextParseException


// ***** VDMTOOLS START Name=JavaTextParseException KEEP=NO
    public JavaTextParseException(final JavaLangString s, final Integer errorOffset_1)
            throws CGException
    {
        super(s);
        ((JavaTextParseException) this).errorOffset = UTIL.NumberToInt(UTIL.clone(errorOffset_1));
    }
// ***** VDMTOOLS END Name=JavaTextParseException

}

;
