//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Tue 30-Oct-2001 by the VDM++ JAVA Code Generator
// (v6.7.19 - Mon 29-Oct-2001)
//
// Supported compilers:
// jdk1.3
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO

// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package jp.vdmtools.VDM.jdk;

// ***** VDMTOOLS END Name=package


// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.vdmtools.VDM.CGException;
import jp.vdmtools.VDM.UTIL;

// ***** VDMTOOLS END Name=imports


public class JavaUtilStringTokenizer extends JavaLangObject  {

    private java.util.StringTokenizer wrappedObject = null;

// ***** VDMTOOLS START Name=JavaUtilStringTokenizer KEEP=NO
    public JavaUtilStringTokenizer() throws CGException {
    }
// ***** VDMTOOLS END Name=JavaUtilStringTokenizer


// ***** VDMTOOLS START Name=hasMoreTokens KEEP=NO
    public Boolean hasMoreTokens() throws CGException {
        return new Boolean(wrappedObject.hasMoreTokens());
    }
// ***** VDMTOOLS END Name=hasMoreTokens

    public JavaLangString nextToken() throws CGException {
	return new JavaLangString(wrappedObject.nextToken());
    }



// ***** VDMTOOLS START Name=JavaUtilStringTokenizer KEEP=NO
    public JavaUtilStringTokenizer(final quotes.NIL var_1_1) throws CGException {
        this();
        isNil = (Boolean) UTIL.clone(new Boolean(true));
    }
// ***** VDMTOOLS END Name=JavaUtilStringTokenizer


// ***** VDMTOOLS START Name=JavaUtilStringTokenizer KEEP=NO
    public JavaUtilStringTokenizer(final JavaLangString str) throws CGException {
	wrappedObject = new java.util.StringTokenizer(str.toSeqOfChar());
    }
// ***** VDMTOOLS END Name=JavaUtilStringTokenizer


// ***** VDMTOOLS START Name=JavaUtilStringTokenizer KEEP=NO
    public JavaUtilStringTokenizer(final JavaLangString str, final JavaLangString delim) throws CGException {
	wrappedObject = new java.util.StringTokenizer(str.toSeqOfChar(),
						      delim.toSeqOfChar());
    }
// ***** VDMTOOLS END Name=JavaUtilStringTokenizer


// ***** VDMTOOLS START Name=JavaUtilStringTokenizer KEEP=NO
    public JavaUtilStringTokenizer(final JavaLangString str, final JavaLangString delim, final Boolean returnDelims) throws CGException {
	wrappedObject = new java.util.StringTokenizer(str.toSeqOfChar(),
						      delim.toSeqOfChar(),
						      returnDelims.booleanValue());

    }
// ***** VDMTOOLS END Name=JavaUtilStringTokenizer

}

;
