//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Tue 30-Oct-2001 by the VDM++ JAVA Code Generator
// (v6.7.19 - Mon 29-Oct-2001)
//
// Supported compilers:
// jdk1.3
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO

// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package jp.vdmtools.VDM.jdk;

// ***** VDMTOOLS END Name=package


// ***** VDMTOOLS START Name=imports KEEP=NO

import jp.vdmtools.VDM.CGException;
import jp.vdmtools.VDM.UTIL;

// ***** VDMTOOLS END Name=imports


public class JavaUtilConcurrentModificationException extends JavaLangRuntimeException {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
    static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


// ***** VDMTOOLS START Name=JavaUtilConcurrentModificationException KEEP=NO
    public JavaUtilConcurrentModificationException() throws CGException {
	super();
    }
// ***** VDMTOOLS END Name=JavaUtilConcurrentModificationException


// ***** VDMTOOLS START Name=JavaUtilConcurrentModificationException KEEP=NO
    public JavaUtilConcurrentModificationException(final quotes.NIL var_1_1) throws CGException {
        this();
        isNil = Boolean.TRUE;
    }
// ***** VDMTOOLS END Name=JavaUtilConcurrentModificationException


// ***** VDMTOOLS START Name=JavaUtilConcurrentModificationException KEEP=NO
    public JavaUtilConcurrentModificationException(final JavaLangString message) throws CGException {
        super(message);
    }
// ***** VDMTOOLS END Name=JavaUtilConcurrentModificationException

}

;
