# Railway Interlocking Systems.

# ETN : gz appended to rail.vdm.ps
TARGETS = rail.vdm.tar.gz rail.vdm.ps.gz

rail.vdm.tar.gz: rail.vdm durnew.sty miv1.sty spor.pstex_t graph.pstex_t point.pstex_t graphsp.pstex_t sporsig.pstex_t graphsig.pstex_t derail.pstex_t trainpaths.pstex_t pointedges.pstex_t derailedge.pstex_t flankprot2.pstex_t

rail.vdm.ps.gz: rail.vdm.ps

include ../Make.rules
