
# Specification of the Single Transferable Vote

TARGETS = stv.avdm.tar.gz stv.ps.gz

BASEFILE = stv

stv.avdm.tar.gz: stv.avdm stv.tex

stv.dvi: stv.tex stv.avdm.tex

stv.ps.gz: stv.ps

include ../Make.rules
