// FROM CG

#include "AS_anonym-sl.cc"     
#include "CPP_anonym-sl.cc"    

// FROM SPEC MGR

#include "AST_anonym.cc"
#include "NonPrintErr_anonym.cc"
#include "ScriptErr_anonym.cc"  
#include "UnitStatus_anonym.cc" 
#include "ErrorState_anonym.cc" 
#include "Options_anonym.cc"    
#include "ToolColleague_anonym.cc"
#include "VDMUnitElem_anonym.cc"    
#include "BaseTools_anonym.cc"  
#include "Errors_anonym.cc"     
#include "ProjectTypes_anonym.cc" 
#include "ToolKit_anonym.cc"    
#include "BatchErr_anonym.cc"   
#include "FileStatus_anonym.cc" 
#include "PromptErr_anonym.cc"  
#include "ToolMediator_anonym.cc" 
#include "CGRepository_anonym.cc"
#include "Interface_anonym.cc"  
#include "Repository_anonym.cc" 
//#include L"CGBase_anonym.cc"     
#include "UpdateSes_anonym.cc"  
#include "NoneSes_anonym.cc"    
#include "StructSes_anonym.cc"  
#include "FlatSes_anonym.cc"    
#include "UpdateProject_anonym.cc" 
#include "StatusInfo_anonym.cc" 
#include "RepDatabase_anonym.cc" 
