//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at ŒŽ 14-5-2001 by the VDM++ C++ Code Generator
// (v6.7.4 - Sat 12-May-2001)
//
// Supported compilers:
// 	gcc version 2.95.2 on Sun Solaris 2.6, Linux, HP-UX10
// 	VC++ version 6.0 on Windows98, Windows NT
//

//#include "dlclass.h"
#include "metaiv.h"
//#include "Comparable.h"
//#include "Object.h"
#ifdef DEF_Comparable_USERIMPL
#include "Comparable_userimpl.cpp"

#endif

