//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at ŒŽ 14-5-2001 by the VDM++ C++ Code Generator
// (v6.7.4 - Sat 12-May-2001)
//
// Supported compilers:
// 	gcc version 2.95.2 on Sun Solaris 2.6, Linux, HP-UX10
// 	VC++ version 6.0 on Windows98, Windows NT
//

#ifndef __Locale_anonym_h__
#define __Locale_anonym_h__



//#include L"Locale_userdef.h"
#include "metaiv.h"
extern const Quote quote_NIL;

class vdm_Locale;
#ifndef TAG_quote_NIL
#define TAG_quote_NIL (TAG_Locale + 1)
#endif


#include "Locale_anonym.h"
#ifndef TAG_vdm_Locale
#define TAG_vdm_Locale (TAG_Locale + 2)
#endif


#endif // __Locale_anonym_h__

