//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at ŒŽ 14-5-2001 by the VDM++ C++ Code Generator
// (v6.7.4 - Sat 12-May-2001)
//
// Supported compilers:
// 	gcc version 2.95.2 on Sun Solaris 2.6, Linux, HP-UX10
// 	VC++ version 6.0 on Windows98, Windows NT
//

#ifndef __Object_anonym_h__
#define __Object_anonym_h__



//#include L"Object_userdef.h"
#include "metaiv.h"
extern const Quote quote_VOID;

extern const Quote quote_NIL;

class vdm_Object;
class type_cL;
#ifndef TAG_type_cL
#define TAG_type_cL (TAG_Object + 1)
#endif

#ifndef TAG_quote_VOID
#define TAG_quote_VOID (TAG_Object + 2)
#endif

#ifndef TAG_quote_NIL
#define TAG_quote_NIL (TAG_Object + 3)
#endif

#include "Object_anonym.h"
#include "String_anonym.h"
#ifndef TAG_vdm_Object
#define TAG_vdm_Object (TAG_Object + 4)
#endif

#ifndef DECL_type_cL
#define DECL_type_cL 1

class type_cL : public SEQ<Char> {
public:
  type_cL () : SEQ<Char>() {}
  type_cL (const SEQ<Char> &c) : SEQ<Char>(c) {}
  type_cL (const Generic &c) : SEQ<Char>(c) {}
  const wchar_t * GetTypeName () const {
    return L"type_cL";
  }
};
#endif // DECL_type_cL

#endif // __Object_anonym_h__

