//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at ŒŽ 14-5-2001 by the VDM++ C++ Code Generator
// (v6.7.4 - Sat 12-May-2001)
//
// Supported compilers:
// 	gcc version 2.95.2 on Sun Solaris 2.6, Linux, HP-UX10
// 	VC++ version 6.0 on Windows98, Windows NT
//




//#include L"StringBuffer_userdef.h"
#include "metaiv.h"
#include "StringBuffer.h"
#include "StringBuffer.h"
#if !DEF_quote_NIL && DECL_quote_NIL
#define DEF_quote_NIL 1
const Quote quote_NIL(L"NIL");

#endif

