#  Programming language Static semantics and dynamic semantics spec

TARGETS = telephone.vdm.gz telephone.ps.gz

telephone.vdm.gz : telephone.vdm

telephone.ps.gz : telephone.vdm.ps

include ../Make.rules
