//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 25-Sep-97 by the VDM++toC++ Code Generator
// (v6.0 - Thu 25-Sep-97)
//
// Supported compiler: g++ version 2.7.2
//



#include "Rectangle.h"

vdm_Rectangle::vdm_Rectangle() { RegisterAsDerived(vdm_GetId()); }
