//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 25-Sep-97 by the VDM++toC++ Code Generator
// (v6.0 - Thu 25-Sep-97)
//
// Supported compiler: g++ version 2.7.2
//

#ifndef _Square_h
#define _Square_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "CGBase.h"
#include "Rectangle.h"
#include "Rhombus.h"



class vdm_Square : 
  public virtual vdm_Rectangle, 
  public virtual vdm_Rhombus {
public:

  virtual vdm_Square * Get_vdm_Square() { return this; }

  ObjectRef Self() { return ObjectRef(Get_vdm_Square()); }

  int vdm_GetId() { return VDM_Square; }
   vdm_Square();

  virtual ~vdm_Square() {}
};

#endif

