#!/bin/bash


CGHOME=/home/cg
if [ -n "$BASEDIR" ] ; then
  :
else
  BASEDIR=$CGHOME/cgtestenv
fi

export BASEDIR
td=$BASEDIR/testdir

if [ -n "$CGTESTDIR" ] ; then
  :
else
  CGTESTDIR=$CGHOME/test
fi

########################
# USAGE OF THE COMMAND #
########################
usage()
{
  echo "Usage: cg_allpp [-Cg | -Dy] [-s dir] [-i | -sp]" >&2
  echo >&2
  echo "       Runs all VDM-PP test suites " >&2
  echo >&2
  echo "       -Cg       Code generator test (default)." >&2
  echo "       -Dy       Dynamic Semantics test." >&2
  echo >&2
  echo "       -sp       Specification test (default)" >&2
  echo "                 with test coverage information." >&2
  echo "       -i        Implementation test." >&2
  echo "       -s dir    Use specification located in dir." >&2
  echo "                 Default dir: $SPEC" >&2

  echo "       Example: `basename $0` -Dy -i" >&2
  echo >&2
  echo "To turn on debug information, set the enviorment variable DEBUG_ON to -x" >&2
  echo "To change root directory of the testenvironment executables," >&2
  echo "   set BASEDIR to the directory (Current value: $BASEDIR)" >&2
  echo "To change root directory of the testcases," >&2
  echo "   set CGTESTDIR to the directory (Current value: $CGTESTDIR)" >&2
  exit
}


###########################################
# Test on the options of the command line #
###########################################
I="-sp -s"
OPTIONS=false

TESTTYPE=-Cg
IMPSPEC=-i
RTINFO=
FILESUFFIX=".spec"
TYPE="Specification"
FILEEXT=".pp.cg"
CGORDYN="Codegenerator"

while test $# -gt 0 ; do
  case $1 in
    -Cg)     shift;;
    -Dy)     TESTTYPE=$1
             FILEEXT=".pp.dyn"
	     CGORDYN="Dynamic Semantics"
             shift;;
    -s)      SPEC=$2
             DTC="-dtc_on -inv_on -pre_on -post_on"
             shift; shift;;
    -sp)     I=-sp -s
             RTINFO=-r
             shift;;
    -i)      I=-i
             RTINFO=""
             FILESUFFIX=".impl"
	     TYPE="Implementation"
             DTC="-D -I -P -Q"
             shift;;
    *)       usage
             exit;;
  esac
done
 

rm -f *.trace

OPTIONS="$I $SPEC -pp $TESTTYPE $RTINFO"
OUTPUTFILENAME=all.trace
TODAY=`date +%y%m%d`
OUT=$OUTPUTFILENAME$FILEEXT$FILESUFFIX.$IFADOSTYPE.$TODAY

echo "This is $0 processing in `pwd`" > $OUT
echo "Testsuite for PP $CGORDYN $TYPE" >> $OUT
echo "Start: `date`" >> $OUT

$td $OPTIONS $CGTESTDIR/CORE
cat trace >> $OUT
$td $OPTIONS  $CGTESTDIR/PP
cat trace >> $OUT
if [ "$I" = "-i" ] ; then
  $td $OPTIONS $CGTESTDIR/IMPL/PP
  cat trace >> $OUT
fi



if [ "$TESTTYPE" = "-Dy" ] ; then
    $td $OPTIONS $DTC $CGTESTDIR/CORE
    cat trace >> $OUT
    $td $OPTIONS $DTC $CGTESTDIR/PP
    cat trace >> $OUT
    if [ "$I" = "-i" ] ; then
        $td $OPTIONS $DTC $CGTESTDIR/IMPL/PP
        cat trace >> $OUT
    fi
fi

