package java.lang;


public final class Character {
public static final  int MIN_RADIX;
public static final  int MAX_RADIX;
public static char MIN_VALUE = ' ';
public static char MAX_VALUE = 'z';
//public static final  Class TYPE;
public static final  byte UNASSIGNED;
public static final  byte UPPERCASE_LETTER;
public static final  byte LOWERCASE_LETTER;
public static final  byte TITLECASE_LETTER;
public static final  byte MODIFIER_LETTER;
public static final  byte OTHER_LETTER;
public static final  byte NON_SPACING_MARK;
public static final  byte ENCLOSING_MARK;
public static final  byte COMBINING_SPACING_MARK;
public static final  byte DECIMAL_DIGIT_NUMBER;
public static final  byte LETTER_NUMBER;
public static final  byte OTHER_NUMBER;
public static final  byte SPACE_SEPARATOR;
public static final  byte LINE_SEPARATOR;
public static final  byte PARAGRAPH_SEPARATOR;
public static final  byte CONTROL;
public static final  byte FORMAT;
public static final  byte PRIVATE_USE;
public static final  byte SURROGATE;
public static final  byte DASH_PUNCTUATION;
public static final  byte START_PUNCTUATION;
public static final  byte END_PUNCTUATION;
public static final  byte CONNECTOR_PUNCTUATION;
public static final  byte OTHER_PUNCTUATION;
public static final  byte MATH_SYMBOL;
public static final  byte CURRENCY_SYMBOL;
public static final  byte MODIFIER_SYMBOL;
public static final  byte OTHER_SYMBOL;
public Character( char value){};
//public native char charValue();
//public native int hashCode();
//public native boolean equals( Object obj);
//public native String toString();
//public static native boolean isLowerCase( char ch);
//public static native boolean isUpperCase( char ch);
//public static native boolean isTitleCase( char ch);
public static native boolean isDigit( char ch);
//public static native boolean isDefined( char ch);
//public static native boolean isLetter( char ch);
//public static native boolean isLetterOrDigit( char ch);
//public static native boolean isJavaLetter( char ch);
//public static native boolean isJavaLetterOrDigit( char ch);
//public static native boolean isJavaIdentifierStart( char ch);
//public static native boolean isJavaIdentifierPart( char ch);
//public static native boolean isUnicodeIdentifierStart( char ch);
//public static native boolean isUnicodeIdentifierPart( char ch);
//public static native boolean isIdentifierIgnorable( char ch);
//public static native char toLowerCase( char ch);
//public static native char toUpperCase( char ch);
//public static native char toTitleCase( char ch);
//public static native int digit( char ch,  int radix);
//public static native int getNumericValue( char ch);
//public static native boolean isSpace( char ch);
public static native boolean isSpaceChar( char ch);
public static native boolean isWhitespace( char ch);
//public static native boolean isISOControl( char ch);
//public static native int getType( char ch);
//public static native char forDigit( int digit,  int radix);
////public native int compareTo( Character anotherCharacter);
//public native int compareTo( Object o);

}
