{ [ mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 1,9 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 5,3 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 2,3 ),
         mk_DefaultMod`NPoint( 5,3 ) } ) ],
  [ mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 1,9 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 2,3 ),
         mk_DefaultMod`NPoint( 5,3 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 5,3 ) } ) ],
  [ mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 5,3 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 1,9 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 2,3 ),
         mk_DefaultMod`NPoint( 5,3 ) } ) ],
  [ mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 5,3 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 2,3 ),
         mk_DefaultMod`NPoint( 5,3 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 1,9 ) } ) ],
  [ mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 2,3 ),
         mk_DefaultMod`NPoint( 5,3 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 1,9 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 5,3 ) } ) ],
  [ mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 2,3 ),
         mk_DefaultMod`NPoint( 5,3 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 5,3 ) } ),
    mk_DefaultMod`NSeg( 
       { mk_DefaultMod`NPoint( 1,1 ),
         mk_DefaultMod`NPoint( 1,9 ) } ) ] }
