mk_DefaultMod`Realm( 
   { mk_DefaultMod`NPoint( 5,0 ),
     mk_DefaultMod`NPoint( 6,1 ) },
   { mk_DefaultMod`NSeg( 
        { mk_DefaultMod`NPoint( 5,0 ),
          mk_DefaultMod`NPoint( 5,1 ) } ),
     mk_DefaultMod`NSeg( 
        { mk_DefaultMod`NPoint( 5,0 ),
          mk_DefaultMod`NPoint( 6,0 ) } ),
     mk_DefaultMod`NSeg( 
        { mk_DefaultMod`NPoint( 5,0 ),
          mk_DefaultMod`NPoint( 6,1 ) } ) } )
