function saferSetup = getSaferSetup
saferSetup = ...
   struct( ...
   'sourcepath', 'G:\icon\examples\tmpsaferdemo\matlab-vdm-link\source\', ...
   'mexpath', 'G:\icon\examples\tmpsaferdemo\matlab-vdm-link\', ...
   'saferml', 'G:\icon\examples\tmpsaferdemo\matlab\', ...
   'gui', 'G:\icon\examples\tmpsaferdemo\matlab\gui\', ...
   'datastructures', 'G:\icon\examples\tmpsaferdemo\matlab\datastructures\', ...
   'testlib', 'G:\icon\examples\tmpsaferdemo\matlab\testlib\', ...
   'safersl', 'G:\icon\examples\tmpsaferdemo\safer-sl\', ...
   'saferpp', 'G:\icon\examples\tmpsaferdemo\safer++\', ...
   'programs', 'c:\program files\', ...
   'matlab', 'c:\matlab\', ...
   'OS', 'NT4' ...
   );
