function fig = safergui()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load safergui

h0 = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'DeleteFcn','quitsafer', ...
	'Name','Safer handgrip', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[3 278.25 303 270], ...
	'Resize','off', ...
	'Tag','safergui');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[3.75 31.75 295.5 108.75], ...
	'Style','frame', ...
	'Tag','aahouterframe');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[14.25 43.5 63.75 75], ...
	'Style','frame', ...
	'Tag','aahframe1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[3.75 148.5 295.5 116.25], ...
	'Style','frame', ...
	'Tag','hgouterframe');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[228 159.75 63.75 75], ...
	'Style','frame', ...
	'Tag','hgframe4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[156.75 159.75 63.75 75], ...
	'Style','frame', ...
	'Tag','hgframe3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[85.5 159.75 63.75 75], ...
	'Style','frame', ...
	'Tag','hgframe2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[14.25 159.75 63.75 75], ...
	'Style','frame', ...
	'Tag','hgframe1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[18 205.5 54.75 25.5], ...
	'String','Forward', ...
	'Style','radiobutton', ...
	'Tag','hgforward');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[18 183.75 54.75 25.5], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','hgfboff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[118.25 240 36.75 18.75], ...
	'String','AAH', ...
	'Style','checkbox', ...
	'Tag','hgaah');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 205.5 54.75 25.5], ...
	'String','Left', ...
	'Style','radiobutton', ...
	'Tag','hgtleft');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 163.5 54.75 25.5], ...
	'String','Right', ...
	'Style','radiobutton', ...
	'Tag','hgtright');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[231.75 163.5 54.75 25.5], ...
	'String','Down', ...
	'Style','radiobutton', ...
	'Tag','hgtdown');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[231.75 205.5 54.75 25.5], ...
	'String','Up', ...
	'Style','radiobutton', ...
	'Tag','hgtup');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[89.25 205.5 54.75 25.5], ...
	'String','Pitch up', ...
	'Style','radiobutton', ...
	'Tag','hgpitchup');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[90 163.5 54.75 25.5], ...
	'String','Pitch down', ...
	'Style','radiobutton', ...
	'Tag','hgpitchdown');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[18 163.5 54.75 25.5], ...
	'String','Backward', ...
	'Style','radiobutton', ...
	'Tag','hgbackward');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[157.75 238 135 18.75], ...
	'String',mat2, ...
	'Style','popupmenu', ...
	'Tag','contextswitch', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 240 56.25 15], ...
	'String','Hand grib', ...
	'Style','text', ...
	'Tag','hgtext');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[89.25 183.75 54.75 25.5], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','hgpudoff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[231.75 183.75 54.75 24.75], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','hgtudoff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 183.75 54.75 24.75], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','hgtlroff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[14.25 119.5 93.75 15], ...
	'String','AAH control output', ...
	'Style','text', ...
	'Tag','aahtext');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[18 48.75 54.75 25.5], ...
	'String','Yaw right', ...
	'Style','radiobutton', ...
	'Tag','aahyawright');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[18 67.5 54.75 25.5], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','aahylroff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[18 88.5 54.75 25.5], ...
	'String','Yaw left', ...
	'Style','radiobutton', ...
	'Tag','aahyawleft');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[85.5 43.5 63.75 75], ...
	'Style','frame', ...
	'Tag','aahframe2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[156.75 43.5 63.75 75], ...
	'Style','frame', ...
	'Tag','aahframe3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[89.25 88.5 54.75 25.5], ...
	'String','Pitch up', ...
	'Style','radiobutton', ...
	'Tag','aahpitchup');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[89.25 67.5 54.75 25.5], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','aahpudoff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[89.25 48.75 54.75 25.5], ...
	'String','Pitch down', ...
	'Style','radiobutton', ...
	'Tag','aahpitchdown');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 88.5 54.75 25.5], ...
	'String','Roll left', ...
	'Style','radiobutton', ...
	'Tag','aahrollleft');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 67.5 54.75 25.5], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','aahrlroff', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 48.75 54.75 25.5], ...
	'String','Roll right', ...
	'Style','radiobutton', ...
	'Tag','aahrollright');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[228.25 6 67.5 18.75], ...
	'String','Apply thrust', ...
	'Tag','applythrust');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 205.5 54.75 25.5], ...
	'String','Yaw left', ...
	'Style','radiobutton', ...
	'Tag','hgryawleft', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 183.75 54.75 24.75], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','hgrylroff', ...
	'Value',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[160.5 163.5 54.75 25.5], ...
	'String','Yaw right', ...
	'Style','radiobutton', ...
	'Tag','hgryawright', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[231.75 205.5 54.75 25.5], ...
	'String','Roll left', ...
	'Style','radiobutton', ...
	'Tag','hgrrollleft', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[231.75 183.75 54.75 24.75], ...
	'String','Off', ...
	'Style','radiobutton', ...
	'Tag','hgrrlroff', ...
	'Value',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','safercallback', ...
	'ListboxTop',0, ...
	'Position',[231.75 163.5 54.75 25.5], ...
	'String','Roll right', ...
	'Style','radiobutton', ...
	'Tag','hgrrollright', ...
	'Visible','off');
if nargout > 0, fig = h0; end
