# Formal Semantics of Data Flow Diagrams.

TARGETS = dfdexample.vdm.tar.gz dfdexample.ps.gz

BASEFILE = dfdexample

dfdexample.vdm.tar.gz: dfdexample.vdm

dfdexample.ps.gz: dfdexample.ps

include ../Make.rules
