//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 25-Mar-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _CAST_h
#define _CAST_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CI.h"
#include "REP.h"
#include "CAST_anonym.h"
;
void init_CAST();
TYPE_AS_Expr vdm_CAST_Pattern2Expr(const TYPE_AS_Pattern &);
TYPE_AS_Expr vdm_CAST_PatternName2Expr(const TYPE_AS_PatternName &);
Bool vdm_CAST_pre_PatternName2Expr(const TYPE_AS_PatternName &);

#endif

