//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Thu 25-Mar-99 by the VDM-SLtoC++ Code Generator
// (v3.3 - Mon 22-Mar-99)
//
// Supported compilers:
// 	egcs version 1.1 on SunOS4, SunOS5, Linux, HP-UX10
// 	VC++ version 6.0 on Windows95, Windows NT
//

#ifndef _PURE_uPAT_h
#define _PURE_uPAT_h

#include <math.h>
#include "metaiv.h"
#include "cg.h"
#include "cg_aux.h"
#include "AS.h"
#include "CI.h"
#include "FRESH.h"
#include "REP.h"
#include "PURE_uPAT_anonym.h"
;
void init_PURE_uPAT();
type_F7AS_NameCS7AS_NameCS3P vdm_PURE_uPAT_Bind2PureBind(const TYPE_AS_Bind &, const TYPE_PURE_uPAT_Identifiers &);
type_FL7AS_NameCS7AS_NameCS3P vdm_PURE_uPAT_BindList2PureBindList(const TYPE_AS_BindList &, const TYPE_PURE_uPAT_Identifiers &);
type_F7AS_NameCS7AS_NameCS3P vdm_PURE_uPAT_Pattern2PurePattern(const TYPE_AS_Pattern &, const TYPE_PURE_uPAT_Identifiers &);

#endif

