#!/bin/sh   

## Runs a VDM test example for one argument file.

## Output the argument to stdout (for redirect) and
## "/dev/tty" (for user feedback)
echo "VDM Test: '$1'" > /dev/tty
echo "VDM Test: '$1'"

SPEC=../sort.vdm

## Run the specification with argument while collecting
## test coverage information, and write the result to an
## output file.
vdmde -i -R vdm.tc -O $1.res $1 $SPEC

## Check for difference between result of execution
## and expected result.
diff -w $1.res $1.exp
if test $? = 0 ; then
  echo "SUCCESS: Result equals expected result" > /dev/tty
  echo "SUCCESS: Result equals expected result"
else
  echo "FAILURE: Result differs from expected result" > /dev/tty
  echo "FAILURE: Result differs from expected result"
fi

