# Steam-Boiler Specification

TARGETS = boiler.vdm.tar.gz 

boiler.vdm.tar.gz : ACTUATORS.vdm ACTUATORS_TYPES.vdm BOILER_ACTUATORS.vdm \
	BOILER_CAPTORS.vdm BOILER_STATE.vdm BOILER_TYPES.vdm CAPTORS.vdm \
	CAPTORS_TYPES.vdm CONTROLLED_BOILER.vdm IMPLEMENTATION.vdm \
	PHYSICAL_BOILER.vdm PHYSICAL_LAWS.vdm SAFE_ACTIONS.vdm \
	SAFE_BOILER.vdm

include ../Make.rules
