#!/bin/bash

#CLASSES="client_example.jar;ToolboxAPI.jar"
CLASSES=client_example.jar:ToolboxAPI.jar

IFS_BACKUP=$IFS
IFS=$'\n'
PWD=`pwd`
export VDM_SOURCE_LOCATION=${PWD%api/corba}examples/sort/
IFS=$IFS_BACKUP

java -cp $CLASSES client_example -ORBInitRef NameService=corbaloc:iiop:1.0@localhost:2809/NameService

